#!/usr/bin/env python
"""Theme 9: LDS family / women / personal development / pastoral (40 works, individually curated)."""
import subprocess, sys, json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
READY = ROOT / "epub" / "!Ready"
DONE = ROOT / "epub" / "!Done"
EXTRACT = ROOT / "scripts" / "epub_extract.py"

WORKS = [
    ("Adversity - Elaine Cannon.epub",
     "adversity-elaine-cannon", "Elaine Cannon", 35, 60, "opcional",
     "books", "en", ["adversity", "women-authored", "yw-president", "20th-century-lds"],
     "Elaine Cannon (1922-2003), Young Women General President 1978-84. Adversity."),
    ("All Alone, Surviving the Loss of Your Spouse - Kathleen Rawlings Buntin.epub",
     "all-alone-loss-of-spouse-buntin", "Kathleen Rawlings Buntin", 25, 55, "opcional",
     "books", "en", ["grief", "widowhood", "pastoral"],
     "Kathleen Rawlings Buntin. All Alone: Surviving the Loss of Your Spouse."),
    ("Aloha - Chieko N. Okazaki.epub",
     "aloha-okazaki", "Chieko N. Okazaki", 40, 65, "importante",
     "books", "en", ["women-authored", "rs-general-presidency", "cultural-diversity", "20th-century-lds"],
     "Chieko N. Okazaki (1926-2011), RS General Presidency 1990-97. Aloha!, 1995."),
    ("Amulek Alternative, Exercising Agency in a World of Choice - Anne Osborn Poelman.epub",
     "amulek-alternative-poelman", "Anne Osborn Poelman", 30, 60, "opcional",
     "books", "en", ["agency", "women-authored", "book-of-mormon-application"],
     "Anne Osborn Poelman. The Amulek Alternative: Exercising Agency."),
    ("Are My Children Going to Make It Real Help for Teachhe Gospel in the Home - R Wayne Boss & Leslee S Boss.epub",
     "are-my-children-going-to-make-it-boss", "R. Wayne & Leslee S. Boss", 25, 55, "opcional",
     "books", "en", ["parenting", "gospel-in-home", "family"],
     "R. Wayne Boss & Leslee S. Boss. Are My Children Going to Make It?"),
    ("Be of Good Cheer - Marvin J. Ashton.epub",
     "be-of-good-cheer-ashton", "Marvin J. Ashton", 50, 75, "importante",
     "books", "en", ["apostle-authored", "cheerfulness", "pastoral"],
     "Elder Marvin J. Ashton (1915-1994), Q12. Be of Good Cheer, 1987."),
    ("Breaking the Cycle of Compulsive Behavior - Martha Nibley Beck & John C Beck.epub",
     "breaking-cycle-compulsive-beck", "Martha Nibley Beck & John C. Beck", 30, 65, "opcional",
     "books", "en", ["addiction", "compulsive-behavior", "psychology"],
     "Martha & John Beck. Breaking the Cycle of Compulsive Behavior, 1990."),
    ("Celebration_ Ten Principles of More Joyous Living - Jaroldeen Edwards.epub",
     "celebration-edwards", "Jaroldeen Edwards", 25, 55, "opcional",
     "books", "en", ["joy", "women-authored", "self-improvement"],
     "Jaroldeen Edwards. Celebration: Ten Principles of More Joyous Living."),
    ("Chainbreakers - Michele R Sorensen.epub",
     "chainbreakers-sorensen", "Michele R. Sorensen", 25, 55, "opcional",
     "books", "en", ["generational-change", "family-healing", "women-authored"],
     "Michele R. Sorensen. Chainbreakers."),
    ("Christ's Emancipation of New Testament Women (Second Edition) - Lynne Hilton Wilson.epub",
     "christs-emancipation-nt-women-wilson", "Lynne Hilton Wilson", 35, 75, "importante",
     "books", "en", ["new-testament", "women", "biblical-studies", "2nd-ed"],
     "Lynne Hilton Wilson. Christ's Emancipation of NT Women, 2nd ed."),
    ("Christ_s Ideals for Living - Obert C Tanner.epub",
     "christs-ideals-for-living-tanner", "Obert C. Tanner", 35, 70, "opcional",
     "books", "en", ["gospel-living", "mid-20th-century-lds", "byu-philosophy"],
     "Obert C. Tanner (1904-1993), philosopher. Christ's Ideals for Living."),
    ("Crowned in Charity and Power - Amber Richardson.epub",
     "crowned-in-charity-richardson", "Amber Richardson", 25, 55, "opcional",
     "books", "en", ["charity", "women-authored", "temple"],
     "Amber Richardson. Crowned in Charity and Power."),
    ("Digno de Confianza - Robert E. Wells.epub",
     "digno-de-confianza-wells", "Robert E. Wells", 40, 65, "opcional",
     "books", "es", ["seventy-authored", "integrity", "latin-american-lds"],
     "Elder Robert E. Wells (1927-2022), Seventy. Digno de Confianza."),
    ("Divine Connection, Understanding Your Inherent Worth - Lloyd D Newell.epub",
     "divine-connection-newell", "Lloyd D. Newell", 30, 60, "opcional",
     "books", "en", ["inherent-worth", "pastoral"],
     "Lloyd D. Newell. Divine Connection: Understanding Your Inherent Worth."),
    ("Doing the Right Things for the Right Reasons - Scott R Peterson & Richard L Bednar.epub",
     "doing-right-things-peterson-bednar", "Scott R. Peterson & Richard L. Bednar", 30, 65, "opcional",
     "books", "en", ["motivation", "psychology", "byu-psychology"],
     "Scott Peterson & Richard L. Bednar. Doing the Right Things for the Right Reasons."),
    ("Effective Mormon Families, How They See Themselves - Phillip R Kunz & William G Dyer.epub",
     "effective-mormon-families-kunz-dyer", "Phillip R. Kunz & William G. Dyer", 30, 70, "opcional",
     "books", "en", ["family-research", "byu-academic", "sociology"],
     "Phillip R. Kunz & William G. Dyer, BYU. Effective Mormon Families."),
    ("Encircled by Love - Jill C Major & Lauren C Leifson & Hollie C Bevan.epub",
     "encircled-by-love-major", "Jill C. Major, Lauren C. Leifson & Hollie C. Bevan", 25, 55, "opcional",
     "books", "en", ["grief", "loss", "women-authored"],
     "Jill C. Major, Lauren C. Leifson & Hollie C. Bevan. Encircled by Love."),
    ("Escalando el monte hacia la exaltación_ de lo telestial a lo terrestre - Genevieve de Hoyos.epub",
     "escalando-el-monte-exaltacion-hoyos", "Genevieve de Hoyos", 25, 55, "opcional",
     "books", "es", ["exaltation", "kingdoms-of-glory", "latin-american-lds"],
     "Genevieve de Hoyos. Escalando el monte hacia la exaltación."),
    ("Eternal Families - Daniel K Judd & Douglas E. Brinley.epub",
     "eternal-families-judd-brinley", "Daniel K. Judd & Douglas E. Brinley", 35, 70, "importante",
     "books", "en", ["eternal-families", "byu-religious-studies"],
     "Daniel K. Judd & Douglas E. Brinley, BYU. Eternal Families."),
    ("Eve and the Choice Made in Eden - Beverly Campbell.epub",
     "eve-and-choice-made-in-eden-campbell", "Beverly Campbell", 35, 70, "importante",
     "books", "en", ["eve", "fall", "women-theology", "biblical-exegesis"],
     "Beverly Campbell. Eve and the Choice Made in Eden, 2003."),
    ("Every Good Thing, Talks from the 1997 BYU Women_s Corence - Susette Green & Dlora Dalton & Dawn Anderson.epub",
     "every-good-thing-byu-women-1997", "Green, Dalton & Anderson (eds.)", 30, 65, "opcional",
     "books", "en", ["byu-womens-conference", "1997", "anthology"],
     "Every Good Thing: Talks from 1997 BYU Women's Conference."),
    ("Eye to Eye, Heart to Heart - Elaine L Jack.epub",
     "eye-to-eye-heart-to-heart-jack", "Elaine L. Jack", 40, 65, "importante",
     "books", "en", ["women-authored", "rs-general-president", "20th-century-lds"],
     "Elaine L. Jack (1928-2018), Relief Society General President 1990-97. Eye to Eye, Heart to Heart."),
    ("Feed My Sheep, Leadership Ideas for Latter-day Shepherds - Alexander B. Morrison.epub",
     "feed-my-sheep-morrison", "Alexander B. Morrison", 45, 75, "importante",
     "books", "en", ["seventy-authored", "leadership", "pastoral"],
     "Elder Alexander B. Morrison, Seventy. Feed My Sheep: Leadership Ideas for LDS Shepherds."),
    ("Finding Peace in Our Lives - Joseph B Wirthlin.epub",
     "finding-peace-in-our-lives-wirthlin", "Joseph B. Wirthlin", 50, 75, "importante",
     "books", "en", ["apostle-authored", "peace", "pastoral"],
     "Elder Joseph B. Wirthlin (1917-2008), Q12. Finding Peace in Our Lives."),
    ("Finding Peace in Troubled Waters, Ten Life Preservers for When Your Ship Springs a Leak - Art E Berg.epub",
     "finding-peace-troubled-waters-berg", "Art E. Berg", 25, 55, "opcional",
     "books", "en", ["adversity", "disability", "motivation"],
     "Art E. Berg. Finding Peace in Troubled Waters."),
    ("Follow the Living Prophets - Brent L Top & Larry E Dahl & Walter D Bowen.epub",
     "follow-the-living-prophets-top-dahl-bowen", "Brent L. Top, Larry E. Dahl & Walter D. Bowen", 35, 75, "importante",
     "books", "en", ["living-prophets", "byu-religious-studies"],
     "Top, Dahl & Bowen, BYU. Follow the Living Prophets, 1993."),
    ("Great Experience, The - Julia Farr.epub",
     "great-experience-farr", "Julia Farr", 25, 55, "opcional",
     "books", "en", ["women-authored", "conversion"],
     "Julia Farr. The Great Experience."),
    ("Helping Your Children Stay Morally Clean - Allan K Burgess.epub",
     "helping-children-morally-clean-burgess", "Allan K. Burgess", 25, 55, "opcional",
     "books", "en", ["parenting", "morality", "youth"],
     "Allan K. Burgess. Helping Your Children Stay Morally Clean."),
    ("Hephzibah - Emmeline B. Wells.epub",
     "hephzibah-wells", "Emmeline B. Wells", 40, 70, "importante",
     "books", "en", ["rs-general-president", "poetry", "19th-20th-century-lds", "primary-source"],
     "Emmeline B. Wells (1828-1921), RS General President 1910-21. Hephzibah, poetry."),
    ("Heroines of the Restoration - Blythe Darlyn Thatcher & Barbara B. Smith.epub",
     "heroines-of-the-restoration-thatcher-smith", "Blythe Darlyn Thatcher & Barbara B. Smith", 35, 65, "importante",
     "books", "en", ["women-restoration", "rs-general-president-foreword"],
     "Thatcher & Barbara B. Smith (RS General Pres. 1974-84). Heroines of the Restoration."),
    ("Higher Laws, Understanding the Doctrines of Christ - Orrin G Hatch.epub",
     "higher-laws-hatch", "Orrin G. Hatch", 30, 65, "opcional",
     "books", "en", ["gospel-doctrine", "senator"],
     "Sen. Orrin G. Hatch (1934-2022). Higher Laws."),
    ("Holiness of Everyday Life - Joan B MacDonald.epub",
     "holiness-of-everyday-life-macdonald", "Joan B. MacDonald", 25, 55, "opcional",
     "books", "en", ["spirituality", "women-authored", "everyday-life"],
     "Joan B. MacDonald. Holiness of Everyday Life."),
    ("Home Teaching with Purpose and Power - Richard J Marshall.epub",
     "home-teaching-marshall", "Richard J. Marshall", 30, 55, "opcional",
     "books", "en", ["home-teaching", "priesthood", "ministry"],
     "Richard J. Marshall. Home Teaching with Purpose and Power."),
    ("Home with Honor, Helps for Returning Missionaries - Randy L Bott.epub",
     "home-with-honor-bott", "Randy L. Bott", 30, 60, "opcional",
     "books", "en", ["missionary", "returning-missionaries", "byu-religious-studies"],
     "Randy L. Bott, BYU. Home with Honor: Helps for Returning Missionaries."),
    ("House of Glory, Finding Personal Meaning in the Temple - S Michael Wilcox.epub",
     "house-of-glory-wilcox", "S. Michael Wilcox", 35, 70, "importante",
     "books", "en", ["temple", "byu-religious-studies"],
     "S. Michael Wilcox, BYU religion. House of Glory, 1995."),
    ("casa de gloria, Una - S. Michael Wilcox.epub",
     "una-casa-de-gloria-wilcox", "S. Michael Wilcox", 35, 70, "importante",
     "books", "es", ["temple", "byu-religious-studies"],
     "S. Michael Wilcox. Una casa de gloria (Spanish translation of House of Glory)."),
    ("If the Gospel Is True, Then Why Do I Hurt So Much He Latter-day Saint Families - Carroll Hofeling Morris.epub",
     "if-the-gospel-is-true-why-hurt-morris", "Carroll Hofeling Morris", 25, 55, "opcional",
     "books", "en", ["faith-crisis", "family-pain", "women-authored"],
     "Carroll Hofeling Morris. If the Gospel Is True, Why Do I Hurt So Much?"),
    ("In Perfect Balance - Spencer J. Condie.epub",
     "in-perfect-balance-condie", "Spencer J. Condie", 40, 70, "importante",
     "books", "en", ["seventy-authored", "balance", "christlike-living"],
     "Elder Spencer J. Condie, Seventy. In Perfect Balance."),
    ("In the Company of Prophets - Heidi S Swinton.epub",
     "in-company-of-prophets-swinton", "Heidi S. Swinton", 35, 70, "opcional",
     "books", "en", ["prophets", "women-authored", "historian"],
     "Heidi S. Swinton, LDS historian. In the Company of Prophets, 1993."),
    ("In the Eye of the Storm - John H. Groberg.epub",
     "in-the-eye-of-storm-groberg", "John H. Groberg", 45, 70, "importante",
     "books", "en", ["seventy-authored", "missionary", "tonga", "memoir"],
     "Elder John H. Groberg, Seventy. In the Eye of the Storm (Tonga missionary memoir)."),
    ("In the Strength of the Lord I Can Do All Things - Carolyn J. Rasmus.epub",
     "in-the-strength-of-the-lord-rasmus", "Carolyn J. Rasmus", 30, 60, "opcional",
     "books", "en", ["discipleship", "women-authored"],
     "Carolyn J. Rasmus. In the Strength of the Lord I Can Do All Things."),
    ("Invocando los poderes celestiales - Grant Von Harrison.epub",
     "invocando-poderes-celestiales-harrison", "Grant Von Harrison", 30, 60, "opcional",
     "books", "es", ["prayer", "priesthood-power", "byu-religious-studies"],
     "Grant Von Harrison, BYU. Invocando los poderes celestiales (Drawing on the Powers of Heaven)."),
    ("Just for Newlyweds - Brent A. Barlow.epub",
     "just-for-newlyweds-barlow", "Brent A. Barlow", 30, 60, "opcional",
     "books", "en", ["marriage", "newlyweds", "byu-family-life"],
     "Brent A. Barlow, BYU. Just for Newlyweds."),
    ("Knit Together in Love, A Focus for LDS Women in thene C. Pingree & Mary Ellen Edmunds & Carol L. Clark.epub",
     "knit-together-in-love-pingree", "A. C. Pingree, M. E. Edmunds & C. L. Clark", 30, 60, "opcional",
     "books", "en", ["women", "relief-society", "sisterhood"],
     "Pingree, Edmunds & Clark. Knit Together in Love: LDS Women."),
    ("Learning for the Eternities - Marion G Romney.epub",
     "learning-for-the-eternities-romney", "Marion G. Romney", 50, 75, "importante",
     "books", "en", ["first-presidency-authored", "education", "eternal-progression"],
     "Pres. Marion G. Romney (1897-1988), First Presidency. Learning for the Eternities."),
    ("escalada de fe, La - Don - Alan Rekow.epub",
     "la-escalada-de-fe-rekow", "Alan Rekow", 20, 50, "opcional",
     "books", "es", ["faith", "personal-development", "spanish-lds"],
     "Alan Rekow. La escalada de fe."),
    ("Deity and Death - Spencer J Palmer.epub",
     "deity-and-death-palmer", "Spencer J. Palmer (ed.)", 30, 75, "opcional",
     "books", "en", ["death", "comparative-religion", "byu-religious-studies"],
     "Spencer J. Palmer (ed.), BYU. Deity and Death. Symposium on death across religions."),
]

ok = 0
broken = []
for fn, slug, author, auth, rigor, imp, cat, lang, tags, note in WORKS:
    src = READY / fn
    if not src.exists():
        broken.append((fn, "MISSING"))
        continue
    fase0 = ROOT / "proj" / "P4-corpus-expansion" / "fase0" / f"{slug}.fase0.json"
    fase0.write_text(json.dumps({
        "authority": auth, "rigor": rigor, "importance": imp,
        "official": False, "current": True, "context": "book-private",
        "audience": "adult", "tags": tags, "category": cat,
        "author": author, "source_url": None, "note": note,
    }, indent=2), encoding="utf-8")
    cmd = [sys.executable, str(EXTRACT), str(src),
           "--lang", lang, "--category", cat, "--apply",
           "--slug", slug, "--author", author, "--fase0", str(fase0)]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode == 0:
        ok += 1
        src.rename(DONE / fn)
        print(f"  OK {slug}")
    else:
        broken.append((fn, r.stderr[-150:] if r.stderr else "?"))
        print(f"  BROKEN {slug}")

print(f"\nTheme 9 (LDS family/women/personal): {ok} OK, {len(broken)} broken")
for fn, err in broken:
    print(f"  - {fn[:60]}: {err[:100]}")
print(f"\n!Ready={len(list(READY.iterdir()))}  !Done={len(list(DONE.iterdir()))}")
