#!/usr/bin/env python
"""Final sweep A: archive literature+tech, incorporate priority singletons."""
import subprocess, sys, json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
READY = ROOT / "epub" / "!Ready"
DONE = ROOT / "epub" / "!Done"
EXTRACT = ROOT / "scripts" / "epub_extract.py"

ARCHIVE = [
    # Literature (continues user's archive policy)
    "Lyrical Ballads - William Wordsworth.epub",
    "O Pioneers_ - Willa Cather.epub",
    "Paradise Regained - John Milton.epub",
    "Picture of Dorian Gray - Oscar Wilde.epub",
    "Prometheus Bound - Euripides.epub",
    "Pygmalion - George Bernard Shaw.epub",
    "Red Badge of Courage - Stephen Crane.epub",
    "Rime of the Ancient Mariner - Samuel Taylor Coleridge.epub",
    "Robinson Crusoe - Daniel Defoe.epub",
    "Scarlet Letter - Nathaniel Hawthorne.epub",
    "Selected Poems of Ella Wheeler Wilcox - Ella Wheeler Wilcox.epub",
    "Selected Poems of George Herbert - George Herbert.epub",
    "Selected Poems of John Keats - John Keats.epub",
    "Selected Poems of Joyce Kilmer - Joyce Kilmer.epub",
    "Selected Poems of Rupert Brooke - Rupert Brooke.epub",
    "Saint Abe and His Seven Wives _ A Tale of Salt Lake th a Bibliographical Note - Robert Williams Buchanan.epub",  # hostile satire 1872
    # Technical/local/off-topic
    "Scrivener 1.9.7 for Microsoft Windows - Literature & Latte.epub",
    "SQL Data Definition Language - Syntax and Examples - Teradata Information Engineering.epub",
    "SOLICITUD DE ARRENDAMIENTO RENTA CONFIANZA (1) - TOLEDO.epub",
    "Quick Start Guide - John Schember.epub",
    "Quiet Success Thoughts - David L. Olpin.epub",
    "PROPUESTA PARA LAS ACTIVIDADES - PC06.epub",
    "Organízate con eficiencia, resúmen del libro - David Allen.epub",
    "Ruby Bridges - Robert Coles.epub",  # civil rights memoir, marginal relevance
    # IJCSUD dup variants (keep one of each group, archive rest)
    "Principios Básicos sobre Bienestar y Autosuficienc -esia de Jesucristo de los Santos de los Últimos Días.epub",  # dup
    "Preparad todo lo que fuere necesario, La economía faesia de Jesucristo de los Santos de los Últimos Días.epub",  # dup
    "PRINCIPIOS DE LIDERAZGO MANUAL PARA EL MAESTRO - La esia de Jesucristo de los Santos de los Últimos Días.epub",  # dup of el-maestro Religión
    "Our Sisters in the Bible - Jerrie W Hurd.epub",  # dup of 'Jerrie W. Hurd' version
]

WORKS = [
    # Singletons — high-value LDS
    ("Opening the Seven Seals, The Visions of John the Revelator - Richard D Draper.epub",
     "opening-seven-seals-draper", "Richard D. Draper",
     40, 80, "importante", "books", "en",
     ["byu-religious-studies", "revelation", "apocalyptic"],
     "Richard D. Draper, BYU. Opening the Seven Seals, 1991."),
    ("One year in Scandinavia - Erastus Fairbanks Snow.epub",
     "one-year-in-scandinavia-efs", "Erastus Snow",
     45, 75, "importante", "history", "en",
     ["apostle-authored", "scandinavian-mission", "19th-century-lds", "primary-source"],
     "Erastus Snow (1818-1888), Q12. One Year in Scandinavia, 1851."),
    ("Orville Southerland Cox, Pioneer of 1847 - Adelia B. Cox Sidwell.epub",
     "orville-cox-pioneer-sidwell", "Adelia B. Cox Sidwell",
     30, 65, "opcional", "biographies", "en",
     ["pioneer-biography", "1847", "primary-source"],
     "Adelia B. Cox Sidwell. Orville Southerland Cox, Pioneer of 1847."),
    ("Our Sisters in the Bible - Jerrie W. Hurd.epub",
     "our-sisters-in-the-bible-hurd", "Jerrie W. Hurd",
     35, 70, "importante", "books", "en",
     ["women", "bible", "lds-women-studies"],
     "Jerrie W. Hurd. Our Sisters in the Bible."),
    ("Outlines of Mormon Philosophy _ Or the Answers Gh, to the Questions of Life - Lycurgus A. Wilson.epub",
     "outlines-mormon-philosophy-wilson", "Lycurgus A. Wilson",
     30, 70, "opcional", "books", "en",
     ["mormon-philosophy", "early-20th-century-lds"],
     "Lycurgus A. Wilson. Outlines of Mormon Philosophy, 1905."),
    ("Overcoming Depression - Richard King Mower.epub",
     "overcoming-depression-mower", "Richard King Mower",
     25, 60, "opcional", "books", "en",
     ["mental-health", "pastoral"],
     "Richard King Mower. Overcoming Depression."),
    ("Overcoming Personal Loss - Duane E. Hiatt.epub",
     "overcoming-personal-loss-hiatt", "Duane E. Hiatt",
     25, 60, "opcional", "books", "en",
     ["grief", "loss", "pastoral"],
     "Duane E. Hiatt. Overcoming Personal Loss."),
    ("PREPARÉMONOS PARA UN MATRIMONIO ETERNO MANUAL PARA Eesia de Jesucristo de los Santos de los Últimos Días.epub",
     "preparemos-matrimonio-eterno-manual-alumno", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es",
     ["institute", "eternal-marriage", "student-manual"],
     "Preparémonos para un matrimonio eterno — Manual para el alumno (Instituto)."),
    ("PRINCIPIOS DE LIDERAZGO MANUAL PARA EL MAESTRO Religesia de Jesucristo de los Santos de los Últimos Días.epub",
     "principios-liderazgo-manual-maestro", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 75, "importante", "manuals", "es",
     ["institute", "leadership", "teacher-manual"],
     "Principios de Liderazgo — Manual para el maestro (Religión)."),
    ("PROGRAMA DE ESTUDIO DEL EVANGELIO PARA MISIONEROS.19esia de Jesucristo de los Santos de los Últimos Días.epub",
     "programa-estudio-evangelio-misioneros-1986", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     45, 70, "opcional", "manuals", "es",
     ["missionary", "study-program", "1986"],
     "Programa de estudio del Evangelio para misioneros (1986)."),
    ("Parent and Teen, Teamed for Success - Ronald John Zirker.epub",
     "parent-and-teen-zirker", "Ronald John Zirker",
     25, 60, "opcional", "books", "en",
     ["parenting", "teens", "byu-family-life"],
     "Ronald John Zirker. Parent and Teen: Teamed for Success."),
    ("Perla de Gran Precio_ Manual para el alumno (Instituesia de Jesucristo de los Santos de los Últimos Días.epub",
     "perla-gran-precio-manual-alumno-instituto", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es",
     ["institute", "pearl-of-great-price", "student-manual"],
     "Perla de Gran Precio — Manual para el alumno (Instituto)."),
    ("Peter and the Popes - A. Burt Horsley.epub",
     "peter-and-the-popes-horsley", "A. Burt Horsley",
     35, 75, "opcional", "books", "en",
     ["byu-religious-studies", "papacy-critique", "apostasy"],
     "A. Burt Horsley, BYU. Peter and the Popes."),
    ("Pilgrim_s Progress - John Bunyan.epub",
     "pilgrims-progress-bunyan", "John Bunyan",
     30, 85, "importante", "reference", "en",
     ["puritan", "christian-allegory", "17th-century", "devotional-classic", "non-lds"],
     "John Bunyan (1628-1688). The Pilgrim's Progress, 1678. Christian allegorical classic, 2nd most-read after Bible for centuries."),
    ("Pioneer Spirit, Modern-Day Stories of Courage and Conviction - Heidi S Swinton.epub",
     "pioneer-spirit-swinton", "Heidi S. Swinton",
     35, 65, "opcional", "books", "en",
     ["lds-historian", "pioneer-stories", "modern-faith"],
     "Heidi S. Swinton. Pioneer Spirit."),
    ("Plan of Salvation, The - John Morgan.epub",
     "plan-of-salvation-morgan", "John Morgan",
     40, 70, "importante", "books", "en",
     ["seventy-authored", "plan-of-salvation", "19th-century-lds", "classic-missionary-tract"],
     "John Morgan (1842-1894), Seventy. The Plan of Salvation — classic missionary tract."),
    ("Preparación para la exaltación, manual para el maestesia de Jesucristo de los Santos de los Últimos Días.epub",
     "preparacion-exaltacion-manual-maestro", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es",
     ["institute", "exaltation-preparation", "teacher-manual"],
     "Preparación para la exaltación — Manual para el maestro."),
    ("Preparad todo lo que fuere necesario, El almacenamia de Jesucristo de los Santos de los Últimos Días.epub",
     "preparad-almacenamiento-ijcsud", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 75, "importante", "manuals", "es",
     ["preparedness", "home-storage", "self-reliance"],
     "Preparad todo lo que fuere necesario — El almacenamiento en el hogar."),
    ("Preparad todo lo que fuere necesario, La economía faesia de Jesucristo de los Santos de los Últimos Días.epub",
     "preparad-economia-familiar-ijcsud", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 75, "importante", "manuals", "es",
     ["preparedness", "family-finance", "self-reliance"],
     "Preparad todo lo que fuere necesario — La economía familiar."),
    ("Principios básicos sobre bienestar y autosuficienciaesia de Jesucristo de los Santos de los Últimos Días.epub",
     "principios-basicos-bienestar-autosuficiencia", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 75, "importante", "manuals", "es",
     ["welfare", "self-reliance", "principles"],
     "Principios básicos sobre bienestar y autosuficiencia."),
    ("Prophecies and Prophetic Promises from the Doctrine and Covenants - Roy W Doxey.epub",
     "prophecies-promises-dc-doxey", "Roy W. Doxey",
     40, 80, "importante", "books", "en",
     ["doctrine-and-covenants", "prophecy", "byu-religious-studies"],
     "Roy W. Doxey. Prophecies and Prophetic Promises from the D&C."),
    ("Prophet and His Work, Essays from General Authoritieth and the Restoration - Various General Authorities.epub",
     "prophet-and-his-work-ga-essays", "Various General Authorities",
     50, 80, "importante", "books", "en",
     ["general-authorities", "joseph-smith", "restoration", "anthology"],
     "Various GAs. The Prophet and His Work: Essays on Joseph Smith and the Restoration."),
    ("Prophets I Have Known - Joseph Anderson.epub",
     "prophets-i-have-known-anderson", "Joseph Anderson",
     40, 75, "importante", "biographies", "en",
     ["seventy-authored", "prophet-biographies", "20th-century-lds"],
     "Elder Joseph Anderson (1889-1992), Seventy. Prophets I Have Known — memoir."),
    ("Prophets, Priesthood Keys, and Succession - Hoyt W Brewster.epub",
     "prophets-priesthood-keys-succession-brewster", "Hoyt W. Brewster",
     35, 75, "importante", "books", "en",
     ["prophetic-succession", "priesthood-keys", "byu-religious-studies"],
     "Hoyt W. Brewster. Prophets, Priesthood Keys, and Succession."),
    ("Prophets, Priests, And Kings - Andrew C. Skinner.epub",
     "prophets-priests-kings-skinner", "Andrew C. Skinner",
     40, 80, "importante", "books", "en",
     ["byu-religious-studies", "ot-themes", "priesthood-orders"],
     "Andrew C. Skinner, BYU. Prophets, Priests, and Kings."),
    ("Proslogion - Excerpts) (Anselm.epub",
     "proslogion-anselm", "Anselm of Canterbury",
     35, 85, "importante", "reference", "en",
     ["scholastic", "11th-century", "ontological-argument", "primary-source", "non-lds"],
     "Anselm of Canterbury (1033-1109). Proslogion (excerpts). Contiene el argumento ontológico."),
    ("Recognitions - Clement of Rome.epub",
     "recognitions-clement", "Clement of Rome (attributed)",
     30, 75, "opcional", "reference", "en",
     ["patristic", "clementine", "pseudepigraphical-christian", "ante-nicene"],
     "Clementine Recognitions (pseudo-Clementine, 3rd-4th c.)."),
    ("Rediscovering the Book of Mormon - Melvin J Thorne & John L Sorenson.epub",
     "rediscovering-bom-sorenson-thorne", "John L. Sorenson & Melvin J. Thorne (eds.)",
     40, 85, "importante", "books", "en",
     ["farms", "book-of-mormon", "byu-academic"],
     "Sorenson & Thorne (eds.), FARMS/BYU. Rediscovering the Book of Mormon."),
    ("Reexploring the Book of Mormon - John W Welch.epub",
     "reexploring-bom-welch", "John W. Welch (ed.)",
     40, 85, "importante", "books", "en",
     ["farms", "book-of-mormon", "byu-academic"],
     "John W. Welch (ed.), FARMS. Reexploring the Book of Mormon, 1992."),
    ("Reflections of a Scientist - Henry Eyring.epub",
     "reflections-of-a-scientist-eyring", "Henry Eyring",
     35, 80, "importante", "books", "en",
     ["science-religion", "chemistry", "lds-scientist", "mid-20th-century"],
     "Henry Eyring (1901-1981), famed chemist and LDS thinker (father of Pres. Henry B. Eyring). Reflections of a Scientist."),
    ("Relación del primer viaje de D. Cristóbal Colón parascubrimiento de las Indias. - Bartolomé de las Casas.epub",
     "relacion-primer-viaje-colon-las-casas-es", "Bartolomé de las Casas",
     30, 85, "importante", "history", "es",
     ["columbus", "primary-source", "16th-century", "indigenous-peoples"],
     "Bartolomé de las Casas (1484-1566). Relación del primer viaje de Colón."),
    ("Relationship of Mormonism and Freemasonry - Anthony W. Ivins.epub",
     "mormonism-and-freemasonry-ivins", "Anthony W. Ivins",
     45, 80, "importante", "books", "en",
     ["apostle-authored", "freemasonry", "temple-ordinances"],
     "Anthony W. Ivins (1852-1934), Q12/First Presidency. The Relationship of Mormonism and Freemasonry, 1934."),
    ("Revelaciones en contexto - Matthew McBride & James Goldberg.epub",
     "revelaciones-en-contexto-mcbride-goldberg-es", "Matthew McBride & James Goldberg",
     50, 85, "importante", "books", "es",
     ["doctrine-and-covenants", "revelations-in-context", "modern-scholarship"],
     "Matthew McBride & James Goldberg. Revelaciones en contexto (ES). Ediciones académicas modernas de la Iglesia."),
    ("Revelación, La - Dallin H. Oaks.epub",
     "revelacion-oaks-es", "Dallin H. Oaks",
     55, 80, "importante", "discourses", "es",
     ["apostle-authored", "revelation", "spanish-discourse"],
     "Pres. Dallin H. Oaks, First Presidency / Q12. La Revelación."),
    ("Revelations of the Restoration - Craig J Ostler & Joseph Fielding McConkie.epub",
     "revelations-of-the-restoration-ostler-mcconkie", "Joseph Fielding McConkie & Craig J. Ostler",
     40, 85, "importante", "books", "en",
     ["doctrine-and-covenants", "byu-religious-studies", "revelation-commentary"],
     "J.F. McConkie & C.J. Ostler. Revelations of the Restoration — comentario sobre DyC."),
    ("Revised and Enhanced History of Joseph Smith By His  Smith & Scot Facer Proctor & Maurine Jensen Proctor.epub",
     "revised-enhanced-history-js-mother", "Lucy Mack Smith; eds. Proctor & Proctor",
     40, 80, "importante", "biographies", "en",
     ["lucy-mack-smith", "enhanced-edition", "primary-source"],
     "Lucy Mack Smith. History of Joseph Smith By His Mother — revised & enhanced edition by Scot & Maurine Proctor, 1996."),
    ("Remembering Joseph - Mark L McConkie.epub",
     "remembering-joseph-m-mcconkie", "Mark L. McConkie",
     35, 75, "opcional", "biographies", "en",
     ["joseph-smith", "eyewitness-accounts", "20th-century-compilation"],
     "Mark L. McConkie. Remembering Joseph — eyewitness accounts of Joseph Smith."),
    ("Religions, Cults and Popular Beliefs - Jessica L. T. Devesa.epub",
     "religions-cults-popular-beliefs-devesa", "Jessica L. T. Devesa",
     20, 60, "opcional", "reference", "en",
     ["comparative-religion", "non-lds"],
     "Jessica L. T. Devesa. Religions, Cults and Popular Beliefs."),
    ("Restoration of the Gospel, The - Osborne J. P. Widtsoe.epub",
     "restoration-of-the-gospel-o-widtsoe", "Osborne J. P. Widtsoe",
     35, 75, "opcional", "books", "en",
     ["restoration", "early-20th-century-lds", "widtsoe-family"],
     "Osborne J. P. Widtsoe. The Restoration of the Gospel."),
    ("Rights of Man - Thomas Paine.epub",
     "rights-of-man-paine", "Thomas Paine",
     25, 80, "importante", "history", "en",
     ["political-philosophy", "18th-century", "french-revolution", "primary-source"],
     "Thomas Paine. Rights of Man, 1791."),
    ("Rights of the Colonists - Samuel Adams.epub",
     "rights-of-the-colonists-adams", "Samuel Adams",
     30, 80, "importante", "history", "en",
     ["political-philosophy", "18th-century", "american-revolution", "primary-source"],
     "Samuel Adams (1722-1803). The Rights of the Colonists, 1772."),
    ("Remarks to Congress - Henry Clay.epub",
     "remarks-to-congress-clay", "Henry Clay",
     25, 75, "opcional", "history", "en",
     ["political-speech", "19th-century", "primary-source", "us-history"],
     "Henry Clay (1777-1852). Remarks to Congress."),
    ("Sacred Temples Ancient and Modern - Richard O. Cowan.epub",
     "sacred-temples-ancient-and-modern-cowan", "Richard O. Cowan",
     40, 80, "importante", "books", "en",
     ["temple", "byu-religious-studies", "ancient-temples"],
     "Richard O. Cowan, BYU. Sacred Temples Ancient and Modern."),
    ("Saturday Night Thoughts - Orson F Whitney.epub",
     "saturday-night-thoughts-whitney-alt", "Orson F. Whitney",
     45, 80, "opcional", "books", "en",
     ["apostle-authored", "dissertations", "alternate-edition"],
     "Elder Orson F. Whitney. Saturday Night Thoughts (alternate edition)."),
    ("Scientific Aspects of Mormonism - Nels L Nelson.epub",
     "scientific-aspects-mormonism-n-nelson", "Nels L. Nelson",
     30, 75, "opcional", "books", "en",
     ["mormonism-science", "early-20th-century-lds"],
     "Nels L. Nelson. Scientific Aspects of Mormonism, 1904."),
    ("Scriptures for the Modern World - C. Wilfred Griggs & Paul R Cheesman.epub",
     "scriptures-for-modern-world-griggs-cheesman", "C. Wilfred Griggs & Paul R. Cheesman (eds.)",
     35, 80, "importante", "books", "en",
     ["byu-religious-studies-center", "scripture-studies"],
     "Griggs & Cheesman (eds.), BYU. Scriptures for the Modern World."),
    ("Selected Letters of Ambrose - Ambrosio.epub",
     "selected-letters-of-ambrose", "Ambrose of Milan",
     40, 85, "importante", "reference", "en",
     ["patristic", "4th-century", "nicene", "ambrose", "primary-source"],
     "Ambrose of Milan (c. 339-397). Selected Letters."),
    ("Selected Letters of Basil the Great - Basil the Great.epub",
     "selected-letters-of-basil", "Basil the Great",
     40, 85, "importante", "reference", "en",
     ["patristic", "4th-century", "cappadocian-father", "basil", "primary-source"],
     "Basil of Caesarea (c. 330-379). Selected Letters."),
]

ok = 0
broken = []
archived = 0

for fn in ARCHIVE:
    p = READY / fn
    if p.exists():
        p.rename(DONE / fn)
        archived += 1

for fn, slug, author, auth, rigor, imp, cat, lang, tags, note in WORKS:
    src = READY / fn
    if not src.exists():
        broken.append((fn, "MISSING"))
        continue
    fase0 = ROOT / "proj" / "P4-corpus-expansion" / "fase0" / f"{slug}.fase0.json"
    fase0.write_text(json.dumps({
        "authority": auth, "rigor": rigor, "importance": imp,
        "official": False, "current": True, "context": "book-private",
        "audience": "adult", "tags": tags, "category": cat,
        "author": author, "source_url": None, "note": note,
    }, indent=2, ensure_ascii=False), encoding="utf-8")
    cmd = [sys.executable, str(EXTRACT), str(src),
           "--lang", lang, "--category", cat, "--apply",
           "--slug", slug, "--author", author, "--fase0", str(fase0)]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode == 0:
        ok += 1
        src.rename(DONE / fn)
        print(f"  OK {slug}")
    else:
        broken.append((fn, r.stderr[-120:] if r.stderr else "?"))
        print(f"  BROKEN {slug}")

print(f"\nFinal sweep A: {ok} OK, {len(broken)} broken, {archived} archived")
for fn, err in broken:
    print(f"  - {fn[:60]}: {err[:100]}")
print(f"\n!Ready={sum(1 for _ in READY.iterdir() if _.is_file())}")
