#!/usr/bin/env python
"""Final sweep C: clear remaining 125 except JPM + Pelé (17 kept for final)."""
import subprocess, sys, json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
READY = ROOT / "epub" / "!Ready"
DONE = ROOT / "epub" / "!Done"
EXTRACT = ROOT / "scripts" / "epub_extract.py"

ARCHIVE = [
    # Literature
    "Wisdom of Father Brown - G K Chesterton.epub",  # detective fiction
    # Secular self-help
    "Sopa de pollo para el alma - Jack Canfield Mark & Víctor Hansen.epub",
    "lugar del alma, El - Gary Zukav.epub",  # new age
    # Intra-dup — "Ven sígueme Primaria" 3 are intra-dups IF older year's annual curriculum replicates. Keep each year.
]

WORKS = [
    # IJCSUD Ven sígueme curriculum (keep all - different years/cohorts)
    ("Libro de Mormón, doctrina del evangelio, manual paraesia de Jesucristo de los Santos de los Últimos Días.epub",
     "bom-doctrina-evangelio-manual", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es", ["book-of-mormon", "gospel-doctrine", "teacher-manual"],
     "Libro de Mormón, Doctrina del Evangelio — manual para el maestro."),
    ("Mi llamamiento como consultor de templo e historia fesia de Jesucristo de los Santos de los Últimos Días.epub",
     "llamamiento-consultor-templo-historia", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     45, 70, "opcional", "manuals", "es", ["temple-work", "family-history", "consultant"],
     "Mi llamamiento como consultor de templo e historia familiar."),
    ("Mi llamamiento como líder de templo e historia familesia de Jesucristo de los Santos de los Últimos Días.epub",
     "llamamiento-lider-templo-historia", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     45, 70, "opcional", "manuals", "es", ["temple-work", "family-history", "leader"],
     "Mi llamamiento como líder de templo e historia familiar."),
    ("Recursos didácticos para quienes enseñan sobre los sia de Jesucristo de los Santos de los Últimos Días.epub",
     "recursos-didacticos-ensenan-santos", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     45, 70, "opcional", "manuals", "es", ["teaching-resources", "santos-volumes"],
     "Recursos didácticos para quienes enseñan sobre los Santos."),
    ("Recursos para enseñar las normas (de la fortaleza paesia de Jesucristo de los Santos de los Últimos Días.epub",
     "recursos-normas-fortaleza-juventud", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     45, 70, "opcional", "manuals", "es", ["for-strength-of-youth", "teaching-resources", "youth"],
     "Recursos para enseñar las normas (Para la Fortaleza de la Juventud)."),
    ("Relatos del Antiguo Testamento para pequeños lectoreesia de Jesucristo de los Santos de los Últimos Días.epub",
     "relatos-at-pequenos-lectores", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     45, 65, "opcional", "reference", "es", ["old-testament", "children", "stories"],
     "Relatos del AT para pequeños lectores."),
    ("Relatos del Libro de Mormón para pequeños lectores -esia de Jesucristo de los Santos de los Últimos Días.epub",
     "relatos-bom-pequenos-lectores", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     45, 65, "opcional", "reference", "es", ["book-of-mormon", "children", "stories"],
     "Relatos del LdM para pequeños lectores."),
    ("Relatos del Nuevo Testamento para pequeños lectores esia de Jesucristo de los Santos de los Últimos Días.epub",
     "relatos-nt-pequenos-lectores", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     45, 65, "opcional", "reference", "es", ["new-testament", "children", "stories"],
     "Relatos del NT para pequeños lectores."),
    ("Reseñas históricas_ Extractos históricos y biogr de Jesucristo de los Santos de los Últimos Días.epub",
     "resenas-historicas-extractos", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "history", "es", ["church-history", "historical-extracts", "biographical"],
     "Reseñas históricas: extractos históricos y biográficos."),
    ("Seminaries and Institutes Fundamentals of Gospel Tesia de Jesucristo de los Santos de los Últimos Días.epub",
     "si-fundamentals-gospel-teaching", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 75, "importante", "manuals", "en", ["seminaries-institutes", "fundamentals-gospel-teaching"],
     "S&I Fundamentals of Gospel Teaching."),
    ("Sobre la instrucción para líderes de templo e historesia de Jesucristo de los Santos de los Últimos Días.epub",
     "instruccion-lideres-templo-historia", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     45, 70, "opcional", "manuals", "es", ["temple-work", "family-history", "leaders"],
     "Sobre la instrucción para líderes de templo e historia familiar."),
    ("Suplemento del Manual de Presidentes de la Iglesia de Jesucristo de los Santos de los Últimos Días.epub",
     "suplemento-manual-presidentes", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 75, "importante", "manuals", "es", ["teachings-of-presidents", "supplement"],
     "Suplemento del Manual de Presidentes de la Iglesia."),
    ("Tabla de correlación de los himnos en diferentes idiesia de Jesucristo de los Santos de los Últimos Días.epub",
     "tabla-correlacion-himnos", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     40, 70, "opcional", "reference", "es", ["hymns", "correlation-table", "multilingual"],
     "Tabla de correlación de los himnos en diferentes idiomas."),
    ("Taller de autosuficiencia laboral, guía del maestro esia de Jesucristo de los Santos de los Últimos Días.epub",
     "taller-autosuficiencia-laboral-maestro", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     30, 60, "opcional", "manuals", "es", ["self-reliance", "employment", "teacher-manual"],
     "Taller de autosuficiencia laboral — Guía del maestro."),
    ("Transmisión de la capacitación anual de Sei de 2020 esia de Jesucristo de los Santos de los Últimos Días.epub",
     "transmision-capacitacion-si-2020", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     45, 70, "opcional", "manuals", "es", ["seminaries-institutes", "training", "2020"],
     "Transmisión de la capacitación anual de S&I 2020."),
    ("Una guía para la ceremonia de graduación de Seminariesia de Jesucristo de los Santos de los Últimos Días.epub",
     "guia-graduacion-seminario", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     40, 65, "opcional", "manuals", "es", ["seminary", "graduation-ceremony"],
     "Una guía para la ceremonia de graduación de Seminario."),
    ("Ven sígueme — Para cuórums del Sacerdocio Aarónica de Jesucristo de los Santos de los Últimos Días.epub",
     "ven-sigueme-aaronic-quorums", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es", ["come-follow-me", "aaronic-priesthood"],
     "Ven sígueme — Para cuórums del Sacerdocio Aarónico."),
    ("Ven sígueme — Para la Escuela Dominical Doctrina y Cesia de Jesucristo de los Santos de los Últimos Días.epub",
     "ven-sigueme-ed-dc", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es", ["come-follow-me", "sunday-school", "doctrine-and-covenants"],
     "Ven sígueme — Para la Escuela Dominical (D&C)."),
    ("Ven sígueme — Para la Escuela Dominical Libro de Moresia de Jesucristo de los Santos de los Últimos Días.epub",
     "ven-sigueme-ed-bom", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es", ["come-follow-me", "sunday-school", "book-of-mormon"],
     "Ven sígueme — Para la Escuela Dominical (LdM)."),
    ("Ven sígueme — Para la Escuela Dominical Nuevo Testamesia de Jesucristo de los Santos de los Últimos Días.epub",
     "ven-sigueme-ed-nt", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es", ["come-follow-me", "sunday-school", "new-testament"],
     "Ven sígueme — Para la Escuela Dominical (NT)."),
    ("Ven sígueme — Para la Primaria Doctrina y Convenios esia de Jesucristo de los Santos de los Últimos Días.epub",
     "ven-sigueme-primaria-dc", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es", ["come-follow-me", "primary", "doctrine-and-covenants"],
     "Ven sígueme — Para la Primaria (D&C)."),
    ("Ven sígueme — Para la Primaria Libro de Mormón 2020 esia de Jesucristo de los Santos de los Últimos Días.epub",
     "ven-sigueme-primaria-bom-2020", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es", ["come-follow-me", "primary", "book-of-mormon", "2020"],
     "Ven sígueme — Para la Primaria (LdM 2020)."),
    ("Ven sígueme — Para la Primaria Nuevo Testamento 2019esia de Jesucristo de los Santos de los Últimos Días.epub",
     "ven-sigueme-primaria-nt-2019", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es", ["come-follow-me", "primary", "new-testament", "2019"],
     "Ven sígueme — Para la Primaria (NT 2019)."),
    # LDS singletons
    ("Notes on Jeremiah - Thomas L. Constable.epub",
     "notes-on-jeremiah-constable", "Thomas L. Constable", 20, 75, "opcional", "reference", "en",
     ["bible-commentary", "jeremiah", "evangelical", "non-lds"],
     "Thomas L. Constable. Notes on Jeremiah."),
    ("Selected Writings of Robert J_ Matthews, Gospel Scholars Series - Robert J Matthews.epub",
     "selected-writings-rj-matthews", "Robert J. Matthews", 40, 80, "importante", "books", "en",
     ["byu-religious-studies", "gospel-scholars-series", "jst-scholar"],
     "Robert J. Matthews (JST scholar). Selected Writings."),
    ("Shadowfall, Reflections on Nurturing Family Values - A. Gail Smith.epub",
     "shadowfall-smith", "A. Gail Smith", 25, 60, "opcional", "books", "en",
     ["family-values", "parenting"],
     "A. Gail Smith. Shadowfall."),
    ("Simeon Solution, One Woman_s Spiritual Odyssey - Anne Osborn Poelman.epub",
     "simeon-solution-poelman", "Anne Osborn Poelman", 30, 65, "opcional", "books", "en",
     ["women-authored", "spiritual-journey", "mixed-faith-marriage"],
     "Anne Osborn Poelman. The Simeon Solution."),
    ("Sinners and Saints _ A Tour Across the States and Ro with Three Months Among the Mormons - Phil Robinson.epub",
     "sinners-and-saints-robinson", "Phil Robinson", 25, 70, "opcional", "history", "en",
     ["19th-century-travel", "external-observer", "mormon-observation", "primary-source"],
     "Phil Robinson. Sinners and Saints, 1883."),
    ("Sketches of Missionary Life - Edwin F. Parry.epub",
     "sketches-missionary-life-eparry", "Edwin F. Parry", 30, 65, "opcional", "history", "en",
     ["missionary", "19th-century-lds", "primary-source"],
     "Edwin F. Parry. Sketches of Missionary Life, 1894."),
    ("Social Contract - Excerpts) (Jean Jacques Rousseau.epub",
     "social-contract-rousseau-excerpts", "Jean-Jacques Rousseau", 25, 80, "importante", "reference", "en",
     ["political-philosophy", "18th-century", "primary-source"],
     "Rousseau. Du Contrat Social (1762) — excerpts."),
    ("Source of the Light, A Witness and Testimony of Jesu Redeemer of All - Scot Facer Proctor & Maurine Jens.epub",
     "source-of-the-light-proctors", "Scot Facer Proctor & Maurine Jensen Proctor", 30, 70, "opcional", "books", "en",
     ["life-of-christ", "devotional"],
     "Scot & Maurine Proctor. Source of the Light."),
    ("Spiritual Plateaus - Glenn L Pace.epub",
     "spiritual-plateaus-pace", "Glenn L. Pace", 45, 70, "importante", "books", "en",
     ["seventy-authored", "spiritual-growth"],
     "Elder Glenn L. Pace, Seventy. Spiritual Plateaus."),
    ("Spiritual Roots of Human Relations - Stephen R Covey.epub",
     "spiritual-roots-human-relations-covey", "Stephen R. Covey", 30, 70, "opcional", "books", "en",
     ["lds-author", "self-help", "relationships"],
     "Stephen R. Covey. Spiritual Roots of Human Relations, 1970."),
    ("Spirituality and Self-Esteem, Developing the Inner Self - Scott R Peterson & Richard L Bednar.epub",
     "spirituality-self-esteem-peterson-bednar", "Scott R. Peterson & Richard L. Bednar",
     30, 70, "opcional", "books", "en",
     ["psychology", "self-esteem", "byu-psychology"],
     "Peterson & Bednar. Spirituality and Self-Esteem."),
    ("Story of the Book of Abraham, Mummies, Manuscripts, and Mormonism - H Donl Peterson.epub",
     "story-book-of-abraham-donl-peterson", "H. Donl Peterson", 40, 80, "importante", "books", "en",
     ["book-of-abraham", "byu-religious-studies", "papyri"],
     "H. Donl Peterson. The Story of the Book of Abraham."),
    ("Story of the Mormons, from the Date of Their Origin to the Year 1901, The - William Alexander Linn.epub",
     "story-of-mormons-1901-linn", "William Alexander Linn", 25, 75, "opcional", "history", "en",
     ["19th-century-external", "hostile-history", "primary-source"],
     "William Alexander Linn. The Story of the Mormons (1902, hostile external)."),
    ("Supporting Saints, Life Stories of Nineteenth-Century Mormons - David J Whittaker & Donald .Q Cannon.epub",
     "supporting-saints-whittaker-cannon", "David J. Whittaker & Donald Q. Cannon (eds.)",
     40, 80, "importante", "biographies", "en",
     ["byu-religious-studies-center", "19th-century-lds", "biographical-anthology"],
     "Whittaker & Cannon (eds.). Supporting Saints: Life Stories of 19th-c Mormons."),
    ("Símbolos mormones - Roberto Vinett Herquiñigo.epub",
     "simbolos-mormones-vinett-es", "Roberto Vinett Herquiñigo", 25, 65, "opcional", "books", "es",
     ["symbolism", "latin-american-lds"],
     "Roberto Vinett Herquiñigo. Símbolos mormones (ES)."),
    ("Tabernáculo (1) - Juan Flores.epub",
     "tabernaculo-flores", "Juan Flores", 20, 65, "opcional", "books", "es",
     ["tabernacle", "ot-studies", "evangelical-leaning"],
     "Juan Flores. El Tabernáculo."),
    ("Teachings of Lorenzo Snow - Lorenzo Snow.epub",
     "teachings-of-lorenzo-snow-primary", "Lorenzo Snow",
     55, 85, "importante", "books", "en",
     ["prophet-authored", "teachings-compilation", "primary-source"],
     "Pres. Lorenzo Snow (1814-1901). Teachings of Lorenzo Snow (Williams ed. primary source)."),
    ("Teens, Temple Marriage, and Eternity - Allan K Burgess.epub",
     "teens-temple-marriage-burgess", "Allan K. Burgess", 30, 65, "opcional", "books", "en",
     ["youth", "temple-marriage", "chastity"],
     "Allan K. Burgess. Teens, Temple Marriage, and Eternity."),
    ("Temple Prayer in Ancient Times - John A. Tvednes.epub",
     "temple-prayer-ancient-times-tvedtnes", "John A. Tvedtnes", 35, 80, "importante", "books", "en",
     ["temple", "ancient-near-east", "prayer", "farms"],
     "John A. Tvedtnes. Temple Prayer in Ancient Times."),
    ("Temples of the Most High - N B Lundwall.epub",
     "temples-of-the-most-high-lundwall", "N. B. Lundwall (comp.)", 35, 75, "importante", "books", "en",
     ["temple", "compilation", "mid-20th-century"],
     "N. B. Lundwall (comp.). Temples of the Most High."),
    ("Templo en la Antigüedad, El - Truman G. Madsen.epub",
     "templo-antiguedad-madsen-es", "Truman G. Madsen (ed.)", 40, 80, "importante", "books", "es",
     ["temple", "ancient-temples", "byu-academic", "spanish-translation"],
     "Truman G. Madsen. El Templo en la Antigüedad (ES translation)."),
    ("Testimonies of the Divinity of the Church - Various ral Authorities & Joseph E Cardon & Samuel O Bennion.epub",
     "testimonies-divinity-church-cardon-bennion", "Various GAs (comp. Cardon & Bennion)",
     45, 75, "importante", "books", "en",
     ["general-authorities", "testimony", "compilation"],
     "Cardon & Bennion comps. Testimonies of the Divinity of the Church."),
    ("The Death of Death in the Death of Christ - John Owen.epub",
     "death-of-death-owen", "John Owen", 25, 80, "importante", "reference", "en",
     ["puritan", "17th-century", "atonement", "particular-redemption", "non-lds"],
     "John Owen (1616-1683). The Death of Death in the Death of Christ, 1647."),
    ("The Great Mosque and Its Ka'ba as an Islamic Tn Temples - Gaye Strathearn & Brian M. Hauglid.epub",
     "great-mosque-kaba-strathearn-hauglid", "Gaye Strathearn & Brian M. Hauglid",
     35, 80, "importante", "books", "en",
     ["byu-academic", "islam", "temples", "comparative-religion"],
     "Strathearn & Hauglid. The Great Mosque and Its Ka'ba as an Islamic Temple."),
    ("The Minor Prophets - Timothy Tow.epub",
     "minor-prophets-tow", "Timothy Tow", 20, 70, "opcional", "reference", "en",
     ["minor-prophets", "evangelical", "non-lds"],
     "Timothy Tow. The Minor Prophets."),
    ("The Relatives of Jesus - Richard Bauckham.epub",
     "relatives-of-jesus-bauckham", "Richard Bauckham", 30, 85, "importante", "reference", "en",
     ["nt-scholarship", "brothers-of-jesus", "modern", "non-lds"],
     "Richard Bauckham (Anglican NT scholar). The Relatives of Jesus."),
    ("The Story of a Kingdom_ A simple explanation of the Bible - Jonny Gibson.epub",
     "story-of-a-kingdom-gibson", "Jonny Gibson", 20, 60, "opcional", "reference", "en",
     ["bible-overview", "evangelical", "non-lds"],
     "Jonny Gibson. The Story of a Kingdom."),
    ("The Temple in Time and Eternity - Seven Promisen Letters - Richard D. Draper & Donald W. Parry.epub",
     "temple-time-eternity-draper-parry", "Richard D. Draper & Donald W. Parry",
     40, 85, "importante", "books", "en",
     ["byu-academic", "temple", "seven-promises"],
     "Draper & Parry, BYU. The Temple in Time and Eternity."),
    ("The Translation of the Word - Bobby Graham.epub",
     "translation-of-the-word-graham", "Bobby Graham", 20, 65, "opcional", "reference", "en",
     ["bible-translation", "non-lds"],
     "Bobby Graham. The Translation of the Word."),
    ("The origins of Christmas and the date of Christ's birth - Kurt M. Simmons.epub",
     "origins-christmas-simmons", "Kurt M. Simmons", 25, 70, "opcional", "reference", "en",
     ["christmas-origins", "nativity-chronology"],
     "Kurt M. Simmons. The Origins of Christmas and the Date of Christ's Birth."),
    ("They Knew the Prophet - Hyrum L. Andrus & Helen Mae Andrus.epub",
     "they-knew-the-prophet-andrus", "Hyrum L. Andrus & Helen Mae Andrus", 35, 75, "importante",
     "biographies", "en", ["joseph-smith", "eyewitness-accounts", "byu-theology"],
     "H. L. & Helen M. Andrus. They Knew the Prophet — eyewitness accounts."),
    ("Things I Wish I_d Known Sooner - Jaroldeen Edwards.epub",
     "things-known-sooner-j-edwards", "Jaroldeen Edwards", 25, 60, "opcional", "books", "en",
     ["women-authored", "reflections"],
     "Jaroldeen Edwards. Things I Wish I'd Known Sooner."),
    ("This Nation Shall Endure - Ezra Taft Benson.epub",
     "this-nation-shall-endure-benson", "Ezra Taft Benson", 55, 80, "importante", "books", "en",
     ["prophet-authored", "us-constitution", "patriotism"],
     "Pres. Ezra Taft Benson (1899-1994). This Nation Shall Endure, 1977."),
    ("Thomas Jefferson - Edward Ellis.epub",
     "thomas-jefferson-ellis", "Edward S. Ellis", 20, 70, "opcional", "biographies", "en",
     ["us-presidents", "19th-century-biography"],
     "Edward S. Ellis. Thomas Jefferson, 1898."),
    ("Thriving on Our Differences - Karen Lynn Davidson.epub",
     "thriving-differences-davidson", "Karen Lynn Davidson", 30, 65, "opcional", "books", "en",
     ["relationships", "diversity"],
     "Karen Lynn Davidson. Thriving on Our Differences."),
    ("Tinkling Cymbals and Sounding Brass, The Art of Tellmith and Brigham Young - David J Whittaker & Hugh Ni.epub",
     "tinkling-cymbals-whittaker-nibley", "Hugh Nibley (ed. Whittaker)",
     45, 85, "importante", "books", "en",
     ["hugh-nibley", "byu-academic", "collected-works", "apostasy", "anti-mormonism-critique"],
     "Hugh Nibley (ed. Whittaker). Tinkling Cymbals and Sounding Brass — Vol. 11 of Nibley Collected Works."),
    ("Tolerance, Principles, Practices, Obstacles, Limits - John K Carmack.epub",
     "tolerance-carmack", "John K. Carmack", 45, 70, "opcional", "books", "en",
     ["seventy-authored", "tolerance", "civic-virtue"],
     "Elder John K. Carmack, Seventy. Tolerance."),
    ("Tora oral de los fariseos, La - Pierre Lenhardt & Matthieu Collin.epub",
     "tora-oral-fariseos-lenhardt-collin-es", "Pierre Lenhardt & Matthieu Collin",
     30, 80, "importante", "reference", "es",
     ["oral-torah", "pharisees", "second-temple", "jewish-studies", "non-lds"],
     "Lenhardt & Collin. La Torá oral de los fariseos (ES)."),
    ("Treatise on the Priesthood - John Chrysostom.epub",
     "treatise-priesthood-chrysostom", "John Chrysostom",
     40, 85, "importante", "reference", "en",
     ["patristic", "4th-century", "priesthood", "chrysostom", "primary-source"],
     "John Chrysostom (c. 349-407). De Sacerdotio (Treatise on the Priesthood)."),
    ("Treatises - Cyprian.epub",
     "treatises-cyprian", "Cyprian of Carthage",
     40, 85, "importante", "reference", "en",
     ["patristic", "3rd-century", "ante-nicene", "cyprian", "primary-source"],
     "Cyprian of Carthage. Treatises (various)."),
    ("Twenty-four Hours to Martyrdom - Reed H Blake.epub",
     "24-hours-to-martyrdom-blake", "Reed H. Blake", 30, 70, "opcional",
     "history", "en", ["carthage-jail", "martyrdom", "narrative-history"],
     "Reed H. Blake. Twenty-four Hours to Martyrdom."),
    ("Under the Prophet in Utah; the National Menace of a stcraft - Frank J. Cannon & Harvey Jerrold O'Higgins.epub",
     "under-prophet-utah-cannon-ohiggins", "Frank J. Cannon & Harvey J. O'Higgins",
     20, 65, "opcional", "history", "en",
     ["early-20th-century-external", "anti-mormon", "frank-j-cannon", "primary-source"],
     "Frank J. Cannon (excom. son of GQ Cannon) & H. J. O'Higgins. Under the Prophet in Utah, 1911 — hostile."),
    ("Understanding Isaiah - Tina M. Peterson.epub",
     "understanding-isaiah-peterson", "Tina M. Peterson", 25, 65, "opcional",
     "books", "en", ["isaiah"],
     "Tina M. Peterson. Understanding Isaiah."),
    ("Understanding Paul - Richard Lloyd Anderson.epub",
     "understanding-paul-rla", "Richard Lloyd Anderson",
     40, 85, "importante", "books", "en", ["byu-religious-studies", "pauline-studies"],
     "Richard Lloyd Anderson, BYU. Understanding Paul, 1983."),
    ("Unknown Testament - Lowell L Bennion.epub",
     "unknown-testament-bennion", "Lowell L. Bennion",
     40, 75, "opcional", "books", "en", ["byu-religious-education", "biblical-studies"],
     "Lowell L. Bennion. The Unknown Testament."),
    ("Unlocking the Old Testament - Victor L. Ludlow.epub",
     "unlocking-ot-ludlow-alt", "Victor L. Ludlow", 40, 80, "importante",
     "books", "en", ["byu-religious-studies", "old-testament", "alternate-edition"],
     "Victor L. Ludlow. Unlocking the Old Testament (alternate edition)."),
    ("Utilitarianism - John Stuart Mill.epub",
     "utilitarianism-mill", "John Stuart Mill", 25, 85, "importante",
     "reference", "en", ["philosophy", "19th-century", "utilitarianism", "primary-source"],
     "John Stuart Mill (1806-1873). Utilitarianism, 1861."),
    ("Utopia - Thomas More.epub",
     "utopia-more", "Thomas More", 25, 80, "importante",
     "reference", "en", ["renaissance", "16th-century", "political-philosophy", "more", "primary-source"],
     "Thomas More (1478-1535). Utopia, 1516."),
    ("Varieties of Religious Experience - William James.epub",
     "varieties-religious-experience-james", "William James", 30, 85, "importante",
     "reference", "en", ["psychology-of-religion", "19th-20th-century", "james", "primary-source"],
     "William James (1842-1910). The Varieties of Religious Experience, 1902."),
    ("Venid, adorémoslo a El, y el Plan - Linda K. Burton.epub",
     "venid-adoremosle-plan-burton-es", "Linda K. Burton", 45, 70, "importante",
     "discourses", "es", ["rs-general-president", "spanish-talk"],
     "Linda K. Burton (RS General President 2012-17). Venid, adorémoslo a Él, y el Plan."),
    ("Venna Hastings_ Story of an Eastern Mormon Convert - Julia Farr.epub",
     "venna-hastings-farr", "Julia Farr", 25, 60, "opcional",
     "biographies", "en", ["conversion-story"],
     "Julia Farr. Venna Hastings: Story of an Eastern Mormon Convert."),
    ("Verso por Verso El Nuevo Testamento, volumen 1, Los cuatro evangeliso - D. Kelly Ogden & Andrew C. Skinner.epub",
     "verso-por-verso-nt-vol-1-ogden-skinner-es", "D. Kelly Ogden & Andrew C. Skinner",
     40, 85, "importante", "books", "es", ["byu-religious-studies", "nt-commentary", "verse-by-verse"],
     "Ogden & Skinner. Verso por Verso: El NT vol. 1, Los Cuatro Evangelios (ES)."),
    ("Visiting Teaching, A Call to Serve - Johanna Flynn & Anita R Canfield.epub",
     "visiting-teaching-flynn-canfield", "Johanna Flynn & Anita R. Canfield", 30, 65, "opcional",
     "books", "en", ["visiting-teaching", "relief-society", "ministering"],
     "Flynn & Canfield. Visiting Teaching: A Call to Serve."),
    ("Vitality of Mormonism - James E Talmage.epub",
     "vitality-of-mormonism-talmage", "James E. Talmage", 55, 85, "importante",
     "books", "en", ["apostle-authored", "classical-apologetics", "early-20th-century"],
     "Elder James E. Talmage (1862-1933), Q12. The Vitality of Mormonism, 1919."),
    ("WAS JESUS REALLY A RABBI - Was Jesus really a Rabbi.epub",
     "was-jesus-really-rabbi", "Anonymous / Unknown", 20, 65, "opcional",
     "reference", "en", ["jesus-as-rabbi", "nt-background"],
     "Was Jesus Really a Rabbi? (anonymous essay)."),
    ("Wars of the Jews - Flavius Josephus.epub",
     "wars-of-the-jews-josephus", "Flavius Josephus", 40, 85, "importante",
     "history", "en", ["classical", "jewish-war", "1st-century", "primary-source", "josephus"],
     "Josephus. The Jewish War (De Bello Judaico), c. 75. Eyewitness of AD 70 destruction."),
    ("We_ll Find the Place, The Mormon Exodus 1846-1848 - Richard E Bennett.epub",
     "well-find-the-place-bennett", "Richard E. Bennett", 40, 85, "importante",
     "history", "en", ["pioneer-exodus", "1846-1848", "byu-academic"],
     "Richard E. Bennett. We'll Find the Place: The Mormon Exodus 1846-1848."),
    ("Wealth of Nations - Adam Smith.epub",
     "wealth-of-nations-adam-smith", "Adam Smith", 25, 90, "importante",
     "reference", "en", ["economics", "18th-century", "primary-source", "classical-economics"],
     "Adam Smith (1723-1790). An Inquiry into the Nature and Causes of the Wealth of Nations, 1776."),
    ("Wentworth Letter, The - Jr. Joseph Smith.epub",
     "wentworth-letter-joseph-smith", "Joseph Smith Jr.", 55, 90, "importante",
     "discourses", "en", ["prophet-authored", "wentworth-letter", "1842", "articles-of-faith-origin", "primary-source"],
     "Joseph Smith. The Wentworth Letter, 1 March 1842 — origin of Articles of Faith."),
    ("What of the Mormons - Gordon B Hinckley.epub",
     "what-of-the-mormons-hinckley", "Gordon B. Hinckley", 55, 75, "importante",
     "books", "en", ["prophet-authored", "mid-20th-century", "missionary-intro"],
     "Pres. Gordon B. Hinckley. What of the Mormons?, 1947."),
    ("When a Loved One Dies - Kathleen Rawlings Buntin.epub",
     "when-loved-one-dies-buntin", "Kathleen Rawlings Buntin", 25, 60, "opcional",
     "books", "en", ["grief", "pastoral"],
     "Kathleen Rawlings Buntin. When a Loved One Dies."),
    ("Window to the Past, A Photographic Panorama of Earlye Doctrine and Covenants - Richard Neitzel Holzapfel.epub",
     "window-to-the-past-holzapfel", "Richard Neitzel Holzapfel", 35, 75, "opcional",
     "history", "en", ["doctrine-and-covenants", "photographic-history", "byu-academic"],
     "R. N. Holzapfel. Window to the Past: Photographic Panorama of Early D&C."),
    ("Woman_s Reach - Belle S. Spafford.epub",
     "womans-reach-spafford", "Belle S. Spafford", 40, 75, "importante",
     "books", "en", ["rs-general-president", "women"],
     "Belle S. Spafford (RS General President 1945-74). A Woman's Reach."),
    ("Women Steadfast in Christ - Marie Cornwall & Dawn Hall Anderson.epub",
     "women-steadfast-in-christ-cornwall", "Marie Cornwall & Dawn Hall Anderson (eds.)",
     35, 70, "opcional", "books", "en", ["byu-womens-conference", "anthology"],
     "Cornwall & Anderson (eds.). Women Steadfast in Christ."),
    ("Women in the Covenant of Grace - Susette Fletcher Green & Dawn Hall Anderson.epub",
     "women-in-covenant-of-grace-green", "Susette Fletcher Green & Dawn Hall Anderson (eds.)",
     35, 70, "opcional", "books", "en", ["byu-womens-conference", "anthology", "covenant"],
     "Green & Anderson (eds.). Women in the Covenant of Grace."),
    ("Women of Mormondom, The - Edward W. Tullidge.epub",
     "women-of-mormondom-tullidge", "Edward W. Tullidge",
     35, 75, "importante", "history", "en",
     ["19th-century-lds", "women-history", "primary-source"],
     "Edward W. Tullidge. The Women of Mormondom, 1877."),
    ("Women of Nauvoo - Richard Neitzel Holzapfel & Jeni Broberg Holzapfel.epub",
     "women-of-nauvoo-holzapfels", "R. N. Holzapfel & Jeni B. Holzapfel",
     35, 75, "importante", "history", "en",
     ["nauvoo", "women-history", "byu-academic"],
     "R. N. & Jeni B. Holzapfel. Women of Nauvoo."),
    ("Women_s Voices, An Untold History of the Latter-day neth W Godfrey & Audrey M Godfrey & Jill Mulvay Derr.epub",
     "womens-voices-untold-history-godfrey", "Godfrey, Godfrey & Derr (eds.)",
     40, 80, "importante", "history", "en",
     ["lds-women-history", "untold-history", "primary-source"],
     "K. W. Godfrey, A. M. Godfrey & J. M. Derr (eds.). Women's Voices: An Untold History of LDS."),
    ("Wondrous Power of a Mother - Marjorie P Hinckley & Gordon B Hinckley.epub",
     "wondrous-power-mother-hinckley", "Marjorie P. Hinckley & Gordon B. Hinckley",
     50, 75, "importante", "books", "en",
     ["prophet-authored", "motherhood"],
     "Gordon B. & Marjorie P. Hinckley. The Wondrous Power of a Mother."),
    ("Words of the Twelve Prophets - Monte S Nyman & Farres H Nyman.epub",
     "words-12-prophets-nyman", "Monte S. Nyman & Farres H. Nyman",
     40, 80, "importante", "books", "en",
     ["minor-prophets", "byu-religious-studies"],
     "Monte S. & Farres H. Nyman. Words of the Twelve Prophets (Minor Prophets)."),
    ("Your Agency, Handle With Care - Spencer J Condie.epub",
     "your-agency-handle-care-condie", "Spencer J. Condie", 45, 70, "opcional",
     "books", "en", ["seventy-authored", "agency"],
     "Elder Spencer J. Condie, Seventy. Your Agency, Handle With Care."),
    ("Youth Leading Youth - Shane R Barker.epub",
     "youth-leading-youth-barker", "Shane R. Barker", 25, 60, "opcional",
     "books", "en", ["youth", "leadership"],
     "Shane R. Barker. Youth Leading Youth."),
    ("libro de Abraham_ Nueva evidencia de su autenticidad y antigüedad, El - O. Preston Robinson.epub",
     "libro-abraham-nueva-evidencia-robinson-es", "O. Preston Robinson",
     35, 75, "importante", "books", "es", ["book-of-abraham", "apologetics", "spanish-lds"],
     "O. Preston Robinson. El libro de Abraham: Nueva evidencia (ES)."),
    ("manuscritos del Mar Muerto, Los - César Vidal Manzanares.epub",
     "manuscritos-mar-muerto-vidal-es", "César Vidal Manzanares",
     25, 75, "opcional", "reference", "es",
     ["dead-sea-scrolls", "second-temple", "spanish"],
     "César Vidal. Los manuscritos del Mar Muerto (ES)."),
    ("muerte de Herodes Agripa, La - Flavio Josefo.epub",
     "muerte-herodes-agripa-josefo-es", "Flavio Josefo",
     30, 80, "opcional", "history", "es",
     ["josephus", "herod-agrippa", "1st-century", "nt-context"],
     "Flavio Josefo. La muerte de Herodes Agripa (ES excerpt)."),
    ("obra misional en la era digital, La - L. Tom Perry.epub",
     "obra-misional-era-digital-perry-es", "L. Tom Perry",
     55, 75, "importante", "discourses", "es",
     ["apostle-authored", "missionary-work", "digital-age", "spanish-talk"],
     "Elder L. Tom Perry. La obra misional en la era digital."),
    ("origen de las especies, El - Charles Darwin.epub",
     "origen-especies-darwin-es", "Charles Darwin",
     25, 90, "importante", "reference", "es",
     ["evolution", "19th-century-science", "primary-source", "darwin"],
     "Charles Darwin. El Origen de las Especies (ES, 1859)."),
    ("otorgador de paz, El - James L. Ferrell.epub",
     "otorgador-paz-ferrell-es", "James L. Ferrell",
     25, 65, "opcional", "books", "es",
     ["peace", "christ-as-peacegiver", "spanish-lds"],
     "James L. Ferrell. El Otorgador de Paz (ES)."),
    ("parábolas de Jesús el Mesías, Las - E. Keith Howick.epub",
     "parabolas-jesus-mesias-howick-es", "E. Keith Howick",
     25, 70, "opcional", "books", "es",
     ["parables", "life-of-christ", "nt-commentary"],
     "E. Keith Howick. Las parábolas de Jesús el Mesías (ES)."),
    ("servicio aceptable - Liahona Marzo de 2010 - liahonaesia de Jesucristo de los Santos de los Últimos Días.epub",
     "servicio-aceptable-liahona-marzo-2010", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 75, "opcional", "discourses", "es",
     ["liahona", "2010", "single-article"],
     "Artículo 'Servicio aceptable' — Liahona marzo 2010."),
    ("teorema de Kólob, El - Lynn M. Hilton.epub",
     "teorema-kolob-hilton-es", "Lynn M. Hilton", 30, 65, "opcional",
     "books", "es", ["kolob", "cosmology", "book-of-abraham"],
     "Lynn M. Hilton. El teorema de Kólob (ES)."),
    ("totalidad de la historia de la Navidad, La - Craig C. Christensen.epub",
     "totalidad-navidad-christensen-es", "Craig C. Christensen",
     45, 70, "importante", "discourses", "es",
     ["seventy-authored", "nativity", "christmas", "spanish-talk"],
     "Elder Craig C. Christensen, Seventy. La totalidad de la historia de la Navidad."),
    ("vida y viajes de Mormon y Moroni, La - Jerry L. Ainsworth.epub",
     "vida-viajes-mormon-moroni-ainsworth-es", "Jerry L. Ainsworth",
     25, 65, "opcional", "books", "es",
     ["mormon-moroni", "book-of-mormon-geography", "mesoamerica"],
     "Jerry L. Ainsworth. La vida y viajes de Mormón y Moroni (ES)."),
]

archived = 0
for fn in ARCHIVE:
    p = READY / fn
    if p.exists():
        p.rename(DONE / fn)
        archived += 1

ok = 0
broken = []
for fn, slug, author, auth, rigor, imp, cat, lang, tags, note in WORKS:
    src = READY / fn
    if not src.exists():
        broken.append((fn, "MISSING"))
        continue
    fase0 = ROOT / "proj" / "P4-corpus-expansion" / "fase0" / f"{slug}.fase0.json"
    fase0.write_text(json.dumps({
        "authority": auth, "rigor": rigor, "importance": imp,
        "official": False, "current": True, "context": "book-private",
        "audience": "adult", "tags": tags, "category": cat,
        "author": author, "source_url": None, "note": note,
    }, indent=2, ensure_ascii=False), encoding="utf-8")
    cmd = [sys.executable, str(EXTRACT), str(src),
           "--lang", lang, "--category", cat, "--apply",
           "--slug", slug, "--author", author, "--fase0", str(fase0)]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode == 0:
        ok += 1
        src.rename(DONE / fn)
    else:
        broken.append((fn, r.stderr[-120:] if r.stderr else "?"))

print(f"Sweep C: {ok} OK, {len(broken)} broken, {archived} archived")
for fn, err in broken[:20]:
    print(f"  - {fn[:60]}: {err[:80]}")
print(f"!Ready={sum(1 for _ in READY.iterdir() if _.is_file())}")
