#!/usr/bin/env python
"""Final sweep B: archive remaining literature/tech, dedupe IJCSUD variants,
incorporate remaining singletons. Leaves JPM (13) + Pelé (4) for last."""
import subprocess, sys, json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
READY = ROOT / "epub" / "!Ready"
DONE = ROOT / "epub" / "!Done"
EXTRACT = ROOT / "scripts" / "epub_extract.py"

ARCHIVE = [
    # Literature
    "Little Women - Louisa May Alcott.epub",
    "Luces de Bohemia - Ramon del Valle-Inclan.epub",
    "Man in the Iron Mask - Alexandre Dumas.epub",
    "Merry Adventures of Robin Hood - Howard Pyle.epub",
    "Moby Dick - Herman Melville.epub",
    "Notes from the Underground - Fyodor Dostoevsky.epub",
    "Silas Marner - George Eliot.epub",
    "Song of Hiawatha - Henry Wadsworth Longfellow.epub",
    "Songs of Innocence and of Experience - William Blake.epub",
    "Spirits in Bondage_ A Cycle of Lyrics - C. S. Lewis.epub",  # Lewis poetry, atheist period
    "Steep Trails - John Muir.epub",
    "Stories of the Badger State - Reuben Gold Thwaites.epub",
    "Stories of the Railroad - John A. Hill.epub",
    "Story of Chester Lawrence _ Being the Completed Acctant Part in _Piney Ridge Cottage_ - Nephi Anderson.epub",  # LDS novel
    "Swiss Family Robinson - Johann David Wyss.epub",
    "Tarzan of the Apes - Edgar Rice Burroughs.epub",
    "Twenty Thousand Leagues under the Sea - Jules Verne.epub",
    "Uncle Tom_s Cabin - Harriet Beecher Stowe.epub",
    "Walden - Henry David Thoreau.epub",  # borderline, archive per literature policy
    "White Fang - Jack London.epub",
    "Wuthering Heights - Emily Bront.epub",
    "Mr. Scraggs - Henry Wallace Phillips.epub",  # literature
    "Myths and Legends of the Sioux - Marie McLaughlin.epub",  # folklore
    # Tech/misc/news
    "The Craft of Writing a Reasearch Proposal on Plagiarism and Citation - Eva Hamann.epub",
    "The Dynamics of Terror in Orwell's 1984 - Malcolm R. Thorp.epub",  # literary criticism
    "Study the Bible with Logos_ Jonah 1_1-16 - Logos Pro Team.epub",
    "Microsoft Word - Priesthood Notice -Feb 9 2017.docx esia de Jesucristo de los Santos de los Últimos Días.epub",
    "Mormon apologetics group announces new name _ Deseret News - Mormon apologetics group announces new.epub",
    "oct 2022 conference handout - Amanda Nelson.epub",
    "testimonio y La Conversión, El - Lenovo.epub",  # 'Lenovo' as author = corrupted/irrelevant
    "Motivos - John Schrock.epub",  # unclear
    "Works of Robert G. Ingersoll, Vol. 08 (of 12) _ Dresden Edition—Interviews, The - Robert Green Ingersoll.epub",  # atheist lectures, low value
    # IJCSUD intra-dup variants
    "Material de Dominio de la doctrina para el maestro sia de Jesucristo de los Santos de los Últimos Días.epub",  # dup
    "Material del Dominio de la doctrina para el mae Jesucristo de los Santos de los Últimos Días.epub",  # dup
    "Matrimonio y relaciones familiares, guía para el paresia de Jesucristo de los Santos de los Últimos Días.epub",  # dup
    "Most Correct Book - Monte S Nyman.epub",  # dup of 'Monte S. Nyman'
    "Normas misionales para los discípulos de Jesucristia de Jesucristo de los Santos de los Últimos Días.epub",  # dup
    "Women of Mormondom - Excerpts) (Edward W Tullidge.epub",  # dup of full version
    "Preparad todo lo que fuere necesario_ La economía faesia de Jesucristo de los Santos de los Últimos Días.epub",  # dup underscore variant
    "Nuestra ofrenda en la reunión sacramental (Juan Pablo Marichal [2017]).pdf - Juan Pablo Marichal Catalán.epub",  # dup PDF→epub rename, keep the clean variant
]

WORKS = [
    # High-value LDS singletons
    ("Libro de los mártires - John Fox.epub",
     "libro-de-los-martires-foxe-es", "John Foxe", 30, 70, "opcional",
     "history", "es", ["protestant", "martyrology", "reformation", "spanish-translation"],
     "John Foxe. Libro de los mártires (ES translation of Book of Martyrs, 1563)."),
    ("Life Before - Brent L Top.epub",
     "life-before-top", "Brent L. Top", 40, 75, "importante", "books", "en",
     ["byu-religious-studies", "pre-mortal-existence"],
     "Brent L. Top, BYU. Life Before (pre-mortal existence)."),
    ("Life of Christ - Frederick W. Farrar.epub",
     "life-of-christ-farrar", "Frederick W. Farrar", 25, 85, "importante",
     "reference", "en", ["anglican", "biblical-scholarship", "19th-century", "life-of-christ", "non-lds"],
     "Frederick W. Farrar (1831-1903), Anglican. The Life of Christ, 1874. Classic NT scholarship."),
    ("Life of Constantine - Eusebius of Caesarea.epub",
     "life-of-constantine-eusebius", "Eusebius of Caesarea", 40, 85, "importante",
     "history", "en", ["patristic", "4th-century", "constantine", "primary-source"],
     "Eusebius. Vita Constantini (Life of Constantine), c. 337-339."),
    ("Light unto the World - David B. Haight.epub",
     "light-unto-the-world-haight", "David B. Haight", 50, 75, "importante",
     "books", "en", ["apostle-authored"],
     "Elder David B. Haight (1906-2004), Q12. Light Unto the World."),
    ("Literature of Belief, Sacred Scripture and Religious Experience - Neal A Lambert.epub",
     "literature-of-belief-lambert", "Neal A. Lambert (ed.)", 35, 80, "opcional",
     "books", "en", ["byu-religious-studies-center", "literature", "religious-experience"],
     "Neal A. Lambert (ed.), BYU. Literature of Belief."),
    ("Little Flowers - Francisco de Asís.epub",
     "little-flowers-francis", "Francis of Assisi (traditional)", 30, 75, "opcional",
     "reference", "en", ["franciscan", "14th-century", "devotional", "hagiography", "non-lds"],
     "Francis of Assisi (traditional). The Little Flowers (Fioretti), c. 14th c."),
    ("Live the Good Life - Thomas S Monson.epub",
     "live-the-good-life-monson", "Thomas S. Monson", 55, 80, "importante",
     "books", "en", ["prophet-authored"],
     "Pres. Thomas S. Monson (1927-2018). Live the Good Life."),
    ("Lives of the Noble Grecians and Romans - Plutarch.epub",
     "lives-plutarch", "Plutarch", 30, 85, "importante",
     "history", "en", ["classical", "greek-roman", "biography", "1st-century", "primary-source"],
     "Plutarch (c. 46-120). Parallel Lives. Foundational ancient biography."),
    ("Living with Enthusiasm - L Tom Perry.epub",
     "living-with-enthusiasm-perry", "L. Tom Perry", 55, 75, "importante",
     "books", "en", ["apostle-authored"],
     "Elder L. Tom Perry (1922-2015), Q12. Living with Enthusiasm."),
    ("Lord Needed a Prophet - Susan Arrington Madsen.epub",
     "lord-needed-a-prophet-madsen", "Susan Arrington Madsen", 35, 70, "opcional",
     "biographies", "en", ["prophet-biographies", "youth-audience"],
     "Susan Arrington Madsen. The Lord Needed a Prophet."),
    ("Love Is a Verb - Mary Ellen Edmunds.epub",
     "love-is-a-verb-edmunds", "Mary Ellen Edmunds", 35, 70, "opcional",
     "books", "en", ["women-authored", "charity", "lds-women"],
     "Mary Ellen Edmunds. Love Is a Verb."),
    ("Lydia Knight's History _ The First Book of the Noble Women's Lives - Susa Young Gates.epub",
     "lydia-knight-history-gates", "Susa Young Gates", 35, 75, "importante",
     "biographies", "en", ["19th-century-lds", "women-authored", "noble-womens-lives-series"],
     "Susa Young Gates (1856-1933). Lydia Knight's History, 1883."),
    ("Making Your Home a Missionary Training Center - Joe J Christensen & Barbara K. Christensen.epub",
     "home-as-mtc-christensen", "Joe J. Christensen & Barbara K. Christensen", 40, 70, "opcional",
     "books", "en", ["seventy-authored", "family-missionary"],
     "Joe J. Christensen (Seventy) & Barbara K. Christensen. Making Your Home a Missionary Training Center."),
    ("Marathon of Faith - Rex E Lee & Janet Lee & Jim Bell.epub",
     "marathon-of-faith-lee", "Rex E. Lee, Janet Lee & Jim Bell", 35, 70, "opcional",
     "biographies", "en", ["byu-president", "faith-story"],
     "Rex E. Lee (BYU President 1989-95), Janet Lee & Jim Bell. Marathon of Faith."),
    ("Marriage of Equals - Dennis .L Lythgoe.epub",
     "marriage-of-equals-lythgoe", "Dennis L. Lythgoe", 30, 65, "opcional",
     "books", "en", ["marriage", "equality"],
     "Dennis L. Lythgoe. Marriage of Equals."),
    ("Material del Dominio de la doctrina para el maestrosia de Jesucristo de los Santos de los Últimos Días.epub",
     "material-dominio-doctrina-maestro", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 75, "importante", "manuals", "es",
     ["doctrinal-mastery", "seminaries", "teacher-manual"],
     "Material del Dominio de la doctrina para el maestro."),
    ("Matthew Cowley Speaks - Matthew Cowley.epub",
     "matthew-cowley-speaks", "Matthew Cowley", 50, 80, "importante",
     "books", "en", ["apostle-authored", "pacific", "sermon-compilation"],
     "Elder Matthew Cowley (1897-1953), Q12. Matthew Cowley Speaks."),
    ("Meaning of Truth - Alvin R. Dyer.epub",
     "meaning-of-truth-dyer", "Alvin R. Dyer", 40, 70, "opcional",
     "books", "en", ["apostle-authored", "truth"],
     "Elder Alvin R. Dyer (1903-1977), Q12. The Meaning of Truth."),
    ("Medidas de protección en el uso de la tecnología - Lesia de Jesucristo de los Santos de los Últimos Días.epub",
     "medidas-proteccion-tecnologia-ijcsud", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     45, 65, "opcional", "manuals", "es",
     ["technology", "protection", "youth"],
     "Medidas de protección en el uso de la tecnología."),
    ("Meditations - Marco Aurelio.epub",
     "meditations-marcus-aurelius", "Marcus Aurelius", 35, 85, "importante",
     "reference", "en", ["classical", "stoicism", "2nd-century", "emperor", "primary-source"],
     "Marcus Aurelius (121-180). Meditations. Stoic classic."),
    ("Men of Invention and Industry - Samuel Smiles.epub",
     "men-invention-industry-smiles", "Samuel Smiles", 20, 70, "opcional",
     "books", "en", ["19th-century", "biographical-sketches", "industrial-age", "non-lds"],
     "Samuel Smiles (1812-1904). Men of Invention and Industry."),
    ("Men with a Mission, 1837-1841 - David J Whittaker & Ronald K Esplin & James B. Allen.epub",
     "men-with-mission-1837-1841", "Whittaker, Esplin & Allen", 40, 85, "importante",
     "history", "en", ["byu-academic", "british-mission", "twelve-apostles", "19th-century-lds"],
     "Allen, Esplin & Whittaker. Men with a Mission: The Quorum of the Twelve Apostles in the British Isles 1837-1841."),
    ("Messages for a Happier Life - William B Smart.epub",
     "messages-happier-life-smart", "William B. Smart", 30, 65, "opcional",
     "books", "en", ["deseret-news", "happiness"],
     "William B. Smart. Messages for a Happier Life."),
    ("Messianic Prophecies and Fulfillments - Anna Thompson.epub",
     "messianic-prophecies-thompson", "Anna Thompson", 25, 70, "opcional",
     "books", "en", ["messianic-prophecies", "christology", "bible-study"],
     "Anna Thompson. Messianic Prophecies and Fulfillments."),
    ("Metamorphoses - Ovid.epub",
     "metamorphoses-ovid", "Ovid", 25, 80, "opcional",
     "reference", "en", ["classical", "roman-literature", "mythology", "1st-century", "primary-source"],
     "Ovid (43 BC - 17 AD). Metamorphoses. Classical mythology compendium."),
    ("Metaphysics of Morals - Immanuel Kant.epub",
     "metaphysics-of-morals-kant", "Immanuel Kant", 25, 85, "importante",
     "reference", "en", ["philosophy", "18th-century", "ethics", "kant", "primary-source"],
     "Kant. Metaphysik der Sitten, 1797."),
    ("Method Infinite_ Freemasonry and the Mormon Restorat. Bruno & Joe Steve Swick III & Nicholas S. Literski.epub",
     "method-infinite-freemasonry", "Bruno, Swick & Literski", 30, 75, "importante",
     "books", "en", ["freemasonry", "restoration", "modern-scholarship"],
     "Bruno, Swick & Literski. Method Infinite: Freemasonry and the Mormon Restoration."),
    ("Mormon Menace_ The Confessions of John Doyle Lee, Danite, The - John Doyle Lee & Alfred Henry Lewis.epub",
     "mormon-menace-john-doyle-lee", "John Doyle Lee", 25, 65, "opcional",
     "history", "en", ["mountain-meadows", "john-d-lee", "19th-century-lds", "primary-source"],
     "John D. Lee. The Mormon Menace / Confessions of John Doyle Lee, Danite. Memoir of the Mountain Meadows participant."),
    ("Mormon Prophet, The - L. Dougall.epub",
     "mormon-prophet-dougall", "L. Dougall", 20, 60, "opcional",
     "history", "en", ["19th-century-fiction", "joseph-smith", "external-novel"],
     "L. Dougall (1858-1923). The Mormon Prophet, 1899."),
    ("Mormon Settlement in Arizona _ A Record of Peaceful Conquest of the Desert - James H. McClintock.epub",
     "mormon-settlement-arizona-mcclintock", "James H. McClintock", 30, 75, "importante",
     "history", "en", ["arizona-history", "pioneer-settlement", "early-20th-century"],
     "James H. McClintock (1864-1934). Mormon Settlement in Arizona, 1921."),
    ("Mormon puzzle, and how to solve it, The - R. W. Beers.epub",
     "mormon-puzzle-beers", "R. W. Beers", 15, 55, "opcional",
     "history", "en", ["anti-mormon", "19th-century-external", "primary-source"],
     "R. W. Beers. The Mormon Puzzle (1887 anti-Mormon)."),
    ("Mormonism Unveiled - Parley P Pratt.epub",
     "mormonism-unveiled-pratt", "Parley P. Pratt", 45, 75, "importante",
     "books", "en", ["apostle-authored", "19th-century-lds", "apologetics", "primary-source"],
     "Parley P. Pratt. Mormonism Unveiled, 1838 (response to E.D. Howe's 1834 anti-Mormon work)."),
    ("Mormons and Muslims, Spiritual Foundations and Modern Manifestations - Spencer J Palmer.epub",
     "mormons-and-muslims-palmer", "Spencer J. Palmer (ed.)", 35, 80, "importante",
     "books", "en", ["comparative-religion", "islam", "byu-religious-studies-center"],
     "Spencer J. Palmer (ed.), BYU. Mormons and Muslims, 1983."),
    ("Mormons and the Theatre; or, The History of Theatricals in Utah, The - John S. Lindsay.epub",
     "mormons-and-the-theatre-lindsay", "John S. Lindsay", 20, 70, "opcional",
     "history", "en", ["theatre", "utah-culture", "19th-century"],
     "John S. Lindsay. The Mormons and the Theatre, 1905."),
    ("Mormons_ A Discourse Delivered Before the Historical Society of Pennsylvania, The - Thomas L. Kane.epub",
     "mormons-kane-discourse", "Thomas L. Kane", 40, 75, "importante",
     "history", "en", ["thomas-kane", "ally", "primary-source", "mid-19th-century"],
     "Col. Thomas L. Kane (1822-1883), LDS ally. 'The Mormons': discourse at Historical Society of Pennsylvania, 1850."),
    ("Morning Breaks, Stories of Conversion and Faith in the Former Soviet Union - Howard L Biddulph.epub",
     "morning-breaks-biddulph", "Howard L. Biddulph", 35, 70, "opcional",
     "biographies", "en", ["soviet-union", "conversion-stories", "modern-mission-history"],
     "Howard L. Biddulph. Morning Breaks: Conversion in the Former Soviet Union."),
    ("Most Correct Book - Monte S. Nyman.epub",
     "most-correct-book-nyman", "Monte S. Nyman", 40, 75, "importante",
     "books", "en", ["book-of-mormon", "byu-religious-studies"],
     "Monte S. Nyman, BYU. The Most Correct Book."),
    ("Mothers of the Prophets - Susan Arrington Madsen & Leonard J Arrington.epub",
     "mothers-of-the-prophets-arringtons", "Susan A. Madsen & Leonard J. Arrington", 35, 75, "importante",
     "biographies", "en", ["prophet-mothers", "lds-women", "biographical"],
     "Susan Arrington Madsen & Leonard J. Arrington. Mothers of the Prophets."),
    ("Mount and the Master - Robert E Wells.epub",
     "mount-and-master-wells", "Robert E. Wells", 40, 70, "opcional",
     "books", "en", ["seventy-authored", "sermon-on-the-mount"],
     "Elder Robert E. Wells, Seventy. The Mount and the Master."),
    ("My Neighbor, My Sister, My Friend - Ardeth Greene Kapp.epub",
     "my-neighbor-sister-friend-kapp", "Ardeth Greene Kapp", 40, 70, "opcional",
     "books", "en", ["yw-general-president", "women", "sisterhood"],
     "Ardeth G. Kapp (YW General President 1984-92). My Neighbor, My Sister, My Friend."),
    ("My Parents Married on a Dare and Other Favorite Essays on Life - Carlfred Broderick.epub",
     "parents-married-on-a-dare-broderick", "Carlfred Broderick", 30, 65, "opcional",
     "books", "en", ["byu-family-life", "essays"],
     "Carlfred Broderick. My Parents Married on a Dare."),
    ("My Servant Brigham, Portrait of a Prophet - R Q Shupe & Richard Neitzel Holzapfel.epub",
     "my-servant-brigham-shupe-holzapfel", "R. Q. Shupe & R. N. Holzapfel", 35, 75, "opcional",
     "biographies", "en", ["brigham-young", "photographic-biography"],
     "Shupe & Holzapfel. My Servant Brigham: Portrait of a Prophet."),
    ("NUESTRO LEGADO Una breve historia de La Iglesiade Jesucristo de los Santos de los Últimos Días.epub",
     "nuestro-legado-ijcsud-es", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     55, 80, "importante", "history", "es",
     ["church-history-narrative", "our-heritage", "official"],
     "Nuestro Legado: Una breve historia de la Iglesia (ES)."),
    ("Narrative of the Life of Frederick Douglass - Frederick Douglass.epub",
     "narrative-life-frederick-douglass", "Frederick Douglass", 30, 85, "importante",
     "history", "en", ["abolition", "slave-narrative", "19th-century", "primary-source", "civil-rights-history"],
     "Frederick Douglass (1818-1895). Narrative of the Life, 1845."),
    ("Nauvoo, A Place of Peace, a People of Promise - Glen M Leonard.epub",
     "nauvoo-place-peace-leonard", "Glen M. Leonard", 40, 85, "importante",
     "history", "en", ["nauvoo", "byu-academic", "definitive-history"],
     "Glen M. Leonard. Nauvoo: A Place of Peace, a People of Promise, 2002."),
    ("No Doubt About It - Sheri Dew.epub",
     "no-doubt-about-it-dew", "Sheri Dew", 40, 75, "importante",
     "books", "en", ["rs-general-presidency", "women-authored", "testimony"],
     "Sheri Dew (RS General Presidency 1997-2002). No Doubt About It."),
    ("Normas misionales para los discípulos de Jesucristo esia de Jesucristo de los Santos de los Últimos Días.epub",
     "normas-misionales-discipulos", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es",
     ["missionary-standards", "discipleship", "current"],
     "Normas misionales para los discípulos de Jesucristo."),
    ("Nuestra búsqueda de la felicidad - M. Russell Ballard.epub",
     "nuestra-busqueda-felicidad-ballard-es", "M. Russell Ballard", 50, 75, "importante",
     "books", "es", ["apostle-authored", "happiness", "spanish-translation"],
     "Pres. M. Russell Ballard. Nuestra búsqueda de la felicidad (ES)."),
    ("Nuevo Diccionario Strong Ampliado de Palabras de la Biblia - James Strong.epub",
     "nuevo-diccionario-strong-ampliado-es", "James Strong", 30, 85, "importante",
     "reference", "es", ["strong-concordance", "hebrew-greek", "reference-work", "expanded-edition"],
     "James Strong. Nuevo Diccionario Strong Ampliado (ES expanded edition)."),
    ("Nuevo Testamento, guía de estudio para el miembro deesia de Jesucristo de los Santos de los Últimos Días.epub",
     "nt-guia-miembro-instituto-es", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es",
     ["institute", "nt-study-guide", "student-manual"],
     "Nuevo Testamento: guía de estudio para el miembro (Instituto)."),
    ("Oaths and Oath Taking in the Old Testament - Stephen D. Ricks.epub",
     "oaths-oath-taking-ot-ricks", "Stephen D. Ricks", 35, 85, "importante",
     "books", "en", ["byu-academic", "oaths", "ot-studies", "farms"],
     "Stephen D. Ricks, BYU. Oaths and Oath Taking in the Old Testament."),
    ("Observations on Daniel - Isaac Newton.epub",
     "observations-daniel-newton", "Isaac Newton", 25, 75, "opcional",
     "reference", "en", ["biblical-prophecy", "newton", "17th-18th-century"],
     "Isaac Newton (1643-1727). Observations upon the Prophecies of Daniel, posthumous 1733."),
    ("Octavius - Minucius Felix.epub",
     "octavius-minucius-felix", "Minucius Felix", 35, 80, "opcional",
     "reference", "en", ["patristic", "3rd-century", "ante-nicene", "apologetics", "primary-source"],
     "Minucius Felix (fl. c. 150-270). Octavius. Early Christian apology dialogue."),
    ("Odyssey - Homer.epub",
     "odyssey-homer", "Homer", 25, 85, "opcional",
     "reference", "en", ["classical", "greek-epic", "homer", "primary-source"],
     "Homer. Odyssey (companion to Iliad, previously added)."),
    ("Oedipus the King - Sophocles.epub",
     "oedipus-rex-sophocles", "Sophocles", 25, 80, "opcional",
     "reference", "en", ["classical", "greek-tragedy", "primary-source"],
     "Sophocles. Oedipus Rex."),
    ("Of Heaven and Earth, Reconciling Scientific Thought with LDS Theology - David Clark.epub",
     "heaven-earth-science-lds-clark", "David Clark", 30, 75, "opcional",
     "books", "en", ["science-religion", "lds-science"],
     "David H. Clark. Of Heaven and Earth."),
    ("Of the House of Israel - Ensign Jan. 1991 - ensign - Of the House of Israel.epub",
     "of-the-house-of-israel-ensign-1991", "Ensign magazine", 50, 75, "opcional",
     "discourses", "en", ["ensign", "1991", "house-of-israel", "single-article"],
     "Ensign January 1991 article: Of the House of Israel."),
    ("On Becoming a Disciple Scholar - Various authors & Henry B Eyring.epub",
     "on-becoming-a-disciple-scholar", "Various (ed. Henry B. Eyring)", 50, 80, "importante",
     "books", "en", ["byu-religious-studies-center", "faith-and-learning", "first-presidency-intro"],
     "Various (ed. Henry B. Eyring). On Becoming a Disciple-Scholar."),
    ("On Civil Government - John Locke.epub",
     "on-civil-government-locke", "John Locke", 25, 85, "importante",
     "reference", "en", ["political-philosophy", "17th-century", "locke", "primary-source"],
     "John Locke. Two Treatises of Civil Government, 1689."),
    ("On the Councils - Hilary.epub",
     "on-the-councils-hilary-poitiers", "Hilary of Poitiers", 40, 80, "opcional",
     "reference", "en", ["patristic", "4th-century", "nicene", "hilary", "primary-source"],
     "Hilary of Poitiers (c. 310-367). On the Councils (De Synodis)."),
    ("On the Improvement of the Understanding - Baruch Spinoza.epub",
     "improvement-understanding-spinoza", "Baruch Spinoza", 25, 80, "opcional",
     "reference", "en", ["philosophy", "17th-century", "spinoza", "primary-source"],
     "Baruch Spinoza. Tractatus de Intellectus Emendatione."),
    ("On the Incarnation of the Word - Atanasio.epub",
     "on-the-incarnation-athanasius", "Athanasius of Alexandria", 40, 90, "importante",
     "reference", "en", ["patristic", "4th-century", "nicene", "incarnation", "christology", "primary-source"],
     "Athanasius of Alexandria (c. 296-373). De Incarnatione Verbi. Christological classic."),
    ("One for the Money - Marvin J. Ashton.epub",
     "one-for-the-money-ashton", "Marvin J. Ashton", 50, 75, "importante",
     "books", "en", ["apostle-authored", "finances", "self-reliance"],
     "Elder Marvin J. Ashton. One for the Money."),
    ("MATRIMONIO Y RELACIONES FAMILIARES_ GUÍA DE ESTUDIOsia de Jesucristo de los Santos de los Últimos Días.epub",
     "matrimonio-familia-guia-estudio", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es",
     ["institute", "marriage", "family", "student-guide"],
     "Matrimonio y relaciones familiares — Guía de estudio."),
    ("MATRIMONIO Y RELACIONES FAMILIARES_ MANUAL PARA EL Iesia de Jesucristo de los Santos de los Últimos Días.epub",
     "matrimonio-familia-manual-maestro", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es",
     ["institute", "marriage", "family", "teacher-manual"],
     "Matrimonio y relaciones familiares — Manual para el maestro."),
    ("Manual del alumno para el curso Enseñanzas de los presia de Jesucristo de los Santos de los Últimos Días.epub",
     "ensenanzas-presidentes-alumno", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es",
     ["teachings-of-presidents", "student-manual"],
     "Manual del alumno — Enseñanzas de los presidentes de la Iglesia."),
    ("Manual del maestro para el curso Enseñanzas de los pesia de Jesucristo de los Santos de los Últimos Días.epub",
     "ensenanzas-presidentes-maestro", "La Iglesia de Jesucristo de los Santos de los Últimos Días",
     50, 80, "importante", "manuals", "es",
     ["teachings-of-presidents", "teacher-manual"],
     "Manual del maestro — Enseñanzas de los presidentes de la Iglesia."),
    ("Moral Discourses - Epictetus.epub",
     "moral-discourses-epictetus", "Epictetus", 30, 85, "importante",
     "reference", "en", ["classical", "stoicism", "1st-2nd-century", "primary-source"],
     "Epictetus (c. 55-135). Discourses (Moral Discourses). Stoic classic."),
]

# Execute
archived = 0
for fn in ARCHIVE:
    p = READY / fn
    if p.exists():
        p.rename(DONE / fn)
        archived += 1

ok = 0
broken = []
for fn, slug, author, auth, rigor, imp, cat, lang, tags, note in WORKS:
    src = READY / fn
    if not src.exists():
        broken.append((fn, "MISSING"))
        continue
    fase0 = ROOT / "proj" / "P4-corpus-expansion" / "fase0" / f"{slug}.fase0.json"
    fase0.write_text(json.dumps({
        "authority": auth, "rigor": rigor, "importance": imp,
        "official": False, "current": True, "context": "book-private",
        "audience": "adult", "tags": tags, "category": cat,
        "author": author, "source_url": None, "note": note,
    }, indent=2, ensure_ascii=False), encoding="utf-8")
    cmd = [sys.executable, str(EXTRACT), str(src),
           "--lang", lang, "--category", cat, "--apply",
           "--slug", slug, "--author", author, "--fase0", str(fase0)]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode == 0:
        ok += 1
        src.rename(DONE / fn)
    else:
        broken.append((fn, r.stderr[-120:] if r.stderr else "?"))

print(f"Sweep B: {ok} OK, {len(broken)} broken, {archived} archived")
for fn, err in broken[:15]:
    print(f"  - {fn[:60]}: {err[:80]}")
print(f"!Ready={sum(1 for _ in READY.iterdir() if _.is_file())}")
